
obj-y	+= hiflash.o
obj-y	+= spinor_ids.o spinor_driver.o
obj-y	+= spinand_ids.o spinand_driver.o
obj-y	+= readretry/ nand_ids.o
obj-y	+= regop_intf.o flash_cache.o

obj-$(CONFIG_MTD_HIFMC100)	+= hifmc100/
