obj-y += cpu-hi3798cv200.o
obj-y += hiahci-phy.o
ifdef CONFIG_PM
obj-$(CONFIG_ARM) += hipm_sleep.o
endif
obj-$(CONFIG_CPU_IDLE_HI3798CV2X) 	+= cpuidle-hi3798cv2x.o pm-hi3798c2x.o
obj-$(CONFIG_PM) += hipm.o
obj-y +=  dt_auxdata.o
