#include "tee_common.h"
#include "tee_config.h"
#include "tee_internal_api.h"
#include "ta_framework.h"
#include "sre_access_control.h"

#define DEFAULT_STACK_SIZE      0x4000
#define DEFAULT_HEAP_SIZE       0x10000
#ifdef TEE_DISABLE_CA_SIGN
int g_tee_disable_ca_auth = TEE_DISABLE_CA_SIGN;
#else
int g_tee_disable_ca_auth;
#endif

/*build in service propertys */
TA_property_t build_in_service_property[] = {
	/* uuid               stack  heap  permissions  instance  sessin  alive*/

	{TEE_SERVICE_ECHO,    DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   false, '0', NULL, 0},
	{TEE_SERVICE_STORAGE, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     false,   true, '0', NULL, 0},
	{TEE_SERVICE_UT,      DEFAULT_STACK_SIZE * 2, DEFAULT_HEAP_SIZE, true,     false,  false, '0', NULL, 0},
	{TEE_SERVICE_CRYPT,   DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true, '0', NULL, 0},
	{TEE_SERVICE_EFUSE,   DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true, '0', NULL, 0},
	{TEE_SERVICE_HDCP,    DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true, '0', NULL, 0},
	{TEE_SERVICE_KEYMASTER, DEFAULT_STACK_SIZE * 5, DEFAULT_HEAP_SIZE * 8, true,     true,   true, '0', NULL, 0},
	{TEE_SERVICE_GATEKEEPER, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true, '0', NULL, 0},
	{TEE_SERVICE_SECBOOT, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true, '0', NULL, 0},
	{TEE_SERVICE_REET, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, false,   true, '0', NULL, 0},
	{TEE_SERVICE_TUI_KEYBOARD,  DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, false,   true, '0', NULL, 0},
	{TEE_SERVICE_MDPP,    DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true, '0', NULL, 0},
	{TEE_SERVICE_VDEC,    DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, false,  true, '0', NULL, 0},
	{TEE_SERVICE_SSA, DEFAULT_STACK_SIZE * 2, DEFAULT_HEAP_SIZE * 8, true,     false,   true, '0', NULL, 0},
	{TEE_SERVICE_ANTIROOT, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,    false,   true, '0', NULL, 0},
#ifdef TEE_SUPPORT_HIVCODEC
	{TEE_SERVICE_HIVCODEC,  DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, false, false, '0', NULL, 0},
#endif
};

uint32_t build_in_service_property_num = sizeof(build_in_service_property) / sizeof(build_in_service_property[0]);


TEE_UUID build_in_uuid[] = {TEE_SERVICE_GLOBAL, TEE_SERVICE_STORAGE,
			    TEE_SERVICE_KEYMASTER, TEE_SERVICE_GATEKEEPER, TEE_SERVICE_SECBOOT,
			    TEE_SERVICE_REET, TEE_SERVICE_TUI_KEYBOARD,
			    TEE_SERVICE_MDPP, TEE_SERVICE_VDEC, TEE_SERVICE_SSA, TEE_SERVICE_ANTIROOT,
#ifdef TEE_SUPPORT_HIVCODEC
			    TEE_SERVICE_HIVCODEC,
#endif
};
uint32_t build_in_service_num = sizeof(build_in_uuid) / sizeof(build_in_uuid[0]);

//TA permission control

TA_permission_t ta_permission_config[] = {
	/*internal tasks*/
	{TEE_SERVICE_STORAGE, GENERAL_GROUP_PERMISSION},
	{TEE_SERVICE_CRYPT,   GENERAL_GROUP_PERMISSION},
	{TEE_SERVICE_EFUSE,   EFUSE_GROUP_PERMISSION},
	{TEE_SERVICE_HDCP,    CC_OEM_KEY_GROUP_PERMISSION},
	{TEE_SERVICE_KEYMASTER, MM_GROUP_PERMISSION | KM_ROT_GROUP_PERMISSION | CC_KEY_GROUP2_PERMISSION | RPMB_GENERIC_PERMISSION},
	{TEE_SERVICE_GATEKEEPER, KM_ROT_GROUP_PERMISSION | CC_KEY_GROUP2_PERMISSION},
	{TEE_SERVICE_SECBOOT, SECBOOT_GROUP_PERMISSION | HWIMSG_GROUP_PERMISSION | MDMCALL_GROUP_PERMISSION},
	{TEE_SERVICE_IMAXCRYPTO, CC_KEY_GROUP2_PERMISSION},
	{TEE_SERVICE_MDPP, CC_KEY_GROUP2_PERMISSION},
	{TEE_SERVICE_REET, SMC_GROUP_PERMISSION},
	{TEE_SERVICE_SSA, (CC_KEY_GROUP2_PERMISSION | MM_GROUP_PERMISSION | HDCP_GROUP_PERMISSION)},
	{TEE_SERVICE_VDEC,  VDEC_GROUP_PERMISSION },
	{TEE_SERVICE_ANTIROOT, TIMER_GROUP_PERMISSION | ROOTSTATUS_GROUP_PERMISSION },
#ifdef TEE_SUPPORT_HIVCODEC
	{TEE_SERVICE_HIVCODEC, VDEC_GROUP_PERMISSION},
#endif
	/*dymanic tasks*/
	{TEE_SERVICE_ECHO, ALL_GROUP_PERMISSION},
	{TEE_SERVICE_TUI_DEMO, TUI_GROUP_PERMISSION | TZASC_GROUP_PERMISSION | HWIMSG_GROUP_PERMISSION | MM_GROUP_PERMISSION},
	{TEE_SERVICE_TUI_KEYBOARD, TUI_GROUP_PERMISSION | TZASC_GROUP_PERMISSION | HWIMSG_GROUP_PERMISSION},
	{TEE_SERVICE_UT,      ALL_GROUP_PERMISSION},
	{TEE_SERVICE_KERNELMEMUSAGE,      ALL_GROUP_PERMISSION},
	{TEE_SERVICE_HELLOWORLD,    GENERAL_GROUP_PERMISSION},
	{TEE_SERVICE_TIMER_UT,    TIMER_GROUP_PERMISSION},
	{TEE_SERVICE_PERMCTRL_UT,    GENERAL_GROUP_PERMISSION},
	{TEE_SERVICE_FINGERPRINT,    FP_GROUP_PERMISSION | RPMB_GENERIC_PERMISSION | KM_ROT_GROUP_PERMISSION | CC_KEY_GROUP2_PERMISSION},
	{TEE_FINGERPRINT_SENSOR_CHECK, FP_GROUP_PERMISSION},
	{TEE_FINGERPRINT_COATING_CHECK, FP_GROUP_PERMISSION},
	{TEE_SERVICE_RPMBKEY,    RPMB_GENERIC_PERMISSION | RPMB_SPECIFIC_PERMISSION | CC_KEY_GROUP2_PERMISSION},
	{TEE_SERVICE_SIGNTOOL,   CC_KEY_GROUP2_PERMISSION | RPMB_GENERIC_PERMISSION},
	{TEE_SERVICE_HUAWEIWALLET,  GENERAL_GROUP_PERMISSION},
	{TEE_SERVICE_CRYPTOSMS,  GENERAL_GROUP_PERMISSION},
	{TEE_SERVICE_ALIPAY,  GENERAL_GROUP_PERMISSION},
	{TEE_SERVICE_WECHAT,  GENERAL_GROUP_PERMISSION},
	{TEE_SERVICE_SKYTONE,    TIMER_GROUP_PERMISSION | RPMB_GENERIC_PERMISSION | VSIM_GROUP_PERMISSION | HWIMSG_GROUP_PERMISSION | MDMCALL_GROUP_PERMISSION | CC_KEY_GROUP2_PERMISSION},
	{TEE_SERVICE_Antitheft,    RPMB_GENERIC_PERMISSION | CC_KEY_GROUP2_PERMISSION},
	{TEE_SERVICE_WIDEVINE_DRM,  VDEC_GROUP_PERMISSION},
	{TEE_SERVICE_IFAA,  RPMB_GENERIC_PERMISSION | CC_KEY_GROUP2_PERMISSION},
	{TEE_SERVICE_ENDORSEMENT,  HDCP_GROUP_PERMISSION},
#ifdef FEATURE_IRIS
    {TEE_SERVICE_IRIS,    IRIS_GROUP_PERMISSION | KM_ROT_GROUP_PERMISSION},
#endif
#ifdef TEE_SUPPORT_HIVCODEC
	{TEE_SERVICE_MMZ,  VDEC_GROUP_PERMISSION},
#endif
};

uint32_t dynamic_ta_num = sizeof(ta_permission_config) / sizeof(ta_permission_config[0]);

TA_rpmb_threshold_t ta_rpmb_threshold_config[] = {
	/* DO NOT EDIT */
	{TEE_SERVICE_UT, 0},
	/* DO NOT EDIT */
	{TEE_SERVICE_FINGERPRINT, 0},
	{TEE_SERVICE_RPMBKEY, 10 * 1024}, // byte unit
	{TEE_SERVICE_SKYTONE, 500 * 1024},
	{TEE_SERVICE_Antitheft, 20 * 1024},
	{TEE_SERVICE_SIGNTOOL, 10 * 1024},
	{TEE_SERVICE_KEYMASTER, 50 * 1024},
	{TEE_SERVICE_IFAA, 20 * 1024},
};
uint32_t g_rpmb_ta_num = sizeof(ta_rpmb_threshold_config) / sizeof(ta_rpmb_threshold_config[0]);

