TRUSTEDCORE_LOCAL_CFLAGS := -DPLATFORM_TASK_MEM_BASE_ADDRESS=$(TRUSTEDCORE_TASK_MEM_BASE) \
			-DTASK_MEM_BASE_ADDRESS=$(TRUSTEDCORE_TASK_MEM_BASE) \
			-DTASK_MEM_LOAD_ADDRESS=$(TRUSTEDCORE_TASK_LOAD_BASE) \
			-DTEXT_BASE=$(TRUSTEDCORE_TEXT_BASE) \
			-DKERNEL_MEM_SIZE=$(TRUSTEDCORE_KERNEL_MEM_SIZE) \
			-DTRUSTEDCORE_MEM_SIZE=$(TRUSTEDCORE_MEM_SIZE) \
			-DTRUSTEDCORE_VIRT_BASE=$(TRUSTEDCORE_VIRT_BASE) \
			-DTRUSTEDCORE_RELEASE_VERSION=$(TRUSTEDCORE_VERSION) \
			-DTRUSTEDCORE_PLATFORM_CHOOSE=$(TRUSTEDCORE_PLATFORM_CHOOSE) \
			-DWITH_KIRIN_PLATFORM=$(WITH_KIRIN_PLATFORM) \
			-DTRUSTEDCORE_CHIP_CHOOSE=$(TRUSTEDCORE_CHIP_CHOOSE) \
			-DWITH_CHIP_HI3650=$(WITH_CHIP_HI3650) \
			-DWITH_CHIP_HI6250=$(WITH_CHIP_HI6250) \
			-DWITH_CHIP_HI3660=$(WITH_CHIP_HI3660) \
			-DWITH_CHIP_HI3670=$(WITH_CHIP_HI3670) \
			-DENG_VERSION=$(WITH_ENG_VERSION) \
			-DWITH_BALONG_V722_PLATFORM=$(WITH_BALONG_V722_PLATFORM) \
			-DWITH_DEVCHIP_PLATFORM=$(WITH_DEVCHIP_PLATFORM)

ifeq ($(strip $(TRUSTEDCORE_ASFLAG_SET)), true)
TRUSTEDCORE_LOCAL_ASFLAGS := -DPLATFORM_TASK_MEM_BASE_ADDRESS=$(TRUSTEDCORE_TASK_BASE) \
			-DTASK_MEM_BASE_ADDRESS=$(TRUSTEDCORE_TASK_MEM_BASE) \
			-DTASK_MEM_LOAD_ADDRESS=$(TRUSTEDCORE_TASK_LOAD_BASE) \
			-DTEXT_BASE=$(TRUSTEDCORE_TEXT_BASE) \
			-DKERNEL_MEM_SIZE=$(TRUSTEDCORE_KERNEL_MEM_SIZE) \
			-DTRUSTEDCORE_VIRT_BASE=$(TRUSTEDCORE_VIRT_BASE) \
			-DTRUSTEDCORE_RELEASE_VERSION=$(TRUSTEDCORE_VERSION)
TRUSTEDCORE_LOCAL_ASFLAGS += -DTRUSTEDCORE_PLATFORM_CHOOSE=$(TRUSTEDCORE_PLATFORM_CHOOSE) \
			-DWITH_KIRIN_PLATFORM=$(WITH_KIRIN_PLATFORM) \
			-DTRUSTEDCORE_CHIP_CHOOSE=$(TRUSTEDCORE_CHIP_CHOOSE) \
			-DWITH_CHIP_HI3650=$(WITH_CHIP_HI3650) \
			-DWITH_CHIP_HI6250=$(WITH_CHIP_HI6250) \
			-DWITH_CHIP_HI3660=$(WITH_CHIP_HI3660) \
			-DWITH_CHIP_HI3670=$(WITH_CHIP_HI3670) \
			-DWITH_BALONG_V722_PLATFORM=$(WITH_BALONG_V722_PLATFORM) \
			-DWITH_DEVCHIP_PLATFORM=$(WITH_DEVCHIP_PLATFORM)
endif

ifeq ($(strip $(TRUSTEDCORE_PLATFORM_CHOOSE)), WITH_DEVCHIP_PLATFORM)
	TRUSTEDCORE_LOCAL_CFLAGS  += $(TRUSTEDCORE_DEVCHIP_CFLAGS)
ifeq ($(strip $(TRUSTEDCORE_ASFLAG_SET)), true)
	TRUSTEDCORE_LOCAL_ASFLAGS += $(TRUSTEDCORE_DEVCHIP_ASFLAGS)
endif
endif

ifeq ($(SECURE_TESTSUITE), RTOSck_UT)
TRUSTEDCORE_LOCAL_CFLAGS += -DTESTSUITE_RTOSck_UT
ifeq ($(strip $(TRUSTEDCORE_ASFLAG_SET)), true)
TRUSTEDCORE_LOCAL_ASFLAGS += -DTESTSUITE_RTOSck_UT
endif
WITH_DEBUG_SWITCH :=true
endif
ifeq ($(SECURE_TESTSUITE), RTOSck_PT)
TRUSTEDCORE_LOCAL_CFLAGS += -DTESTSUITE_RTOSck_PT
ifeq ($(strip $(TRUSTEDCORE_ASFLAG_SET)), true)
TRUSTEDCORE_LOCAL_ASFLAGS += -DTESTSUITE_RTOSck_PT
endif
WITH_DEBUG_SWITCH :=true
endif
ifeq ($(SECURE_TESTSUITE), RTOSck_IT)
TRUSTEDCORE_LOCAL_CFLAGS += -DTESTSUITE_RTOSck_IT
ifeq ($(strip $(TRUSTEDCORE_ASFLAG_SET)), true)
TRUSTEDCORE_LOCAL_ASFLAGS += -DTESTSUITE_RTOSck_IT
endif
WITH_DEBUG_SWITCH :=true
endif

ifeq ($(strip $(LPAE_SUPPORT)), 1)
	TRUSTEDCORE_LOCAL_CFLAGS += -DARM_PAE
	TRUSTEDCORE_LOCAL_ASFLAGS += -DARM_PAE
endif
