
ccflags-y := -Idrivers/media/rc

obj-$(CONFIG_IR_NEC_2HDR_40BIT_DECODER)	+= ir-nec-2hdr_40bit_decoder.o
obj-$(CONFIG_IR_NEC_FULL_40BIT_DECODER)	+= ir-nec-full_40bit_decoder.o
obj-$(CONFIG_IR_NEC_FULL_48BIT_DECODER)	+= ir-nec-full_48bit_decoder.o

obj-$(CONFIG_HISI_IR_NEC_SIMPLE_2HDR_GD)	+= ir-keymap-nec-gd.o
obj-$(CONFIG_HISI_IR_NEC_SIMPLE_UPD61261)	+= ir-keymap-nec-rc8a.o
obj-$(CONFIG_HISI_NEC_FULL_DEZHOU)		+= ir-keymap-nec-full-dezhou.o
obj-$(CONFIG_HISI_NEC_FULL_BANK)		+= ir-keymap-nec-bank.o
obj-$(CONFIG_HISI_NEC_SIMPLE_HISILICON)		+= ir-keymap-nec-hisilicon.o
obj-$(CONFIG_HISI_NEC_SIMPLE_BLACK)		+= ir-keymap-nec-black.o
obj-$(CONFIG_HISI_NEC_TC9012)			+= ir-keymap-nec-skyworth-yk.o
obj-$(CONFIG_HISI_EXTENDED_RC5_DONGFANG)	+= ir-keymap-rc5-dongfang.o
obj-$(CONFIG_HISI_SONY)				+= ir-keymap-sony.o
obj-$(CONFIG_HISI_RC5_14BIT_SKYWORTH)		+= ir-keymap-rc5-skyworth.o
obj-$(CONFIG_HISI_RC5_14BIT_LUFENG)		+= ir-keymap-rc5-lufeng.o
obj-$(CONFIG_HISI_RC6_16BIT_PHILIPS)		+= ir-keymap-rc6-philips.o
obj-$(CONFIG_HISI_RC6_32BIT_BGCTV)		+= ir-keymap-rc6-gehua.o

obj-$(CONFIG_HISI_IR)				+= ir-hisi.o

