
obj-$(CONFIG_ARCH_S40)		+= s40/
obj-$(CONFIG_ARCH_HI3798MX)	+= hi3798mx/
obj-$(CONFIG_ARCH_HIFONE)	+= hifone/
obj-$(CONFIG_ARCH_HI3798CV2X)	+= hi3798cv2x/
obj-$(CONFIG_ARCH_HI3798MV2X)	+= hi3798mv2x/
obj-$(CONFIG_ARCH_HI3796MV2X)	+= hi3796mv200/
obj-y		+= clk-hisi.o
obj-$(CONFIG_RESET_CONTROLLER)	+= reset-hisilicon.o
