obj-y += cpu-hi3796mv200.o
obj-y += hiahci-phy.o
ifdef CONFIG_PM
obj-$(CONFIG_ARM) += hipm_sleep.o
endif
obj-$(CONFIG_CPU_IDLE_HI3796MV200) 	+= cpuidle-hi3796mv200.o pm-hi3796mv200.o
obj-$(CONFIG_PM) += hipm.o
obj-y +=  dt_auxdata.o
