
obj-y	+= clk-hi3716cv200.o clk-hi3716mv410.o clk-hifmc100.o
obj-y	+= clk-hisfc350.o clk-hiahci.o clk-hiusb2.o
obj-y	+= clk-hiahci-hi3716mv420.o
obj-y	+= clk-hipcie-hi3716mv420.o
obj-y	+= clk-hiir.o

ccflags-y += -I./drivers/hisilicon/clk
