################################################################################
#    Copyright (C) 2014 Hisilicon STB Development Dept
#    All rights reserved.
#####
#    Create by Cai Zhiyong
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
################################################################################

CFLAGS += -I$(SRCDIR)../

SRCS-y := hinfc610.c hinfc610_gen.c \
	hinfc610_read_retry_hynix_bg_cdie.c \
	hinfc610_read_retry_hynix_bg_bdie.c \
	hinfc610_read_retry_hynix_cg_adie.c \
	hinfc610_read_retry_micron.c  \
	hinfc610_read_retry_samsung.c \
	hinfc610_read_retry_toshiba.c \
	hinfc610_read_retry.c \
	hinfc610_sync.c \
	hinfc620_gen.c \
	hinfc610_sync_onfi_23.c \
	hinfc610_sync_toggle.c
