################################################################################
#     COPYRIGHT (C) 2012 Czyong. Hisilicon
#     All rights reserved.
# 
#     Create by Czyong 2012-12-20
# 
################################################################################

SRCS-$(CONFIG_UART) += uart/
SRCS-y += timer/
SRCS-y += flash/
SRCS-y += irq/
SRCS-$(CONFIG_GENERIC_USB) += usb/

