#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#


ifeq ($(CFG_HI_EXPORT_FLAG),)
    ifneq ($(srctree),)
        KERNEL_DIR := $(srctree)

        SDK_DIR := $(KERNEL_DIR)/../../..
    else
        SDK_DIR := $(CURDIR)/../../../../../../../..
    endif

    include $(SDK_DIR)/base.mak
endif

include $(SDK_DIR)/source/msp/drv/gpu/mali700/kbuild_flags

ccflags-y += -I$(SDK_DIR)/source/msp/drv/gpu/mali700/drivers/base/kds \
		-I$(SDK_DIR)/source/msp/drv/gpu/mali700/include

$(warning "ccflags-y = $(ccflags-y)...")
obj-$(CONFIG_KDS) += kds.o
obj-$(CONFIG_KDS_TEST) += kds_test.o
