
enum HELLO_WORLD_TEST_CMD_ID {
	CMD_ID_CREATE_ONE_TIMER = 0,
	CMD_ID_CREATE_MUTIPLE_TIMER,
	CMD_ID_DESTORY_EXIST_TIMER,
	CMD_ID_DESTORY_NON_EXIST_TIMER,
	CMD_ID_GET_TIMER_EXPIRE_TIME,
	CMD_ID_GET_TIMER_REMAIN_TIME,
	CMD_ID_NO_CALLBACK,
	CMD_ID_CREATE_ONE_TIMER_WITHOUT_CALLBACK,
	CMD_ID_CREATE_ONE_TIMER_ONCE = 8,
	CMD_ID_GET_ONE_TIMER_EXPIRE_ONCE,
	CMD_ID_GET_ONE_TIMER_REMAIN_ONCE,
	CMD_ID_DESTORY_EXIST_TIMER_ONCE,
	CMD_ID_GET_SYS_TIME
};

enum MAIN_CMD_ID {
	CMD_ID_TIMER = 0,
};
