
obj-y	+= clk-hi3798cv200.o
obj-y	+= clk-hiusb2.o
obj-y	+= clk-hiusb3.o
obj-y	+= clk-higpu.o
obj-y	+= clk-hipcie.o
obj-y	+= clk-hiahci.o
obj-y	+= clk-hifmc100.o
obj-y	+= clk-hiir.o

ccflags-y += -I./drivers/hisilicon/clk
