
/**************************************************************************************
*
* statname.h - name mangling macros for static linking
**************************************************************************************/

#ifndef _RESAMPLE_STATNAME_H
#define _RESAMPLE_STATNAME_H

#define HI_RESAMPLE_PRINT(  module_id, fmt...)
#define STAT_PREFIX RES

#define STATCC1(x, y, z) STATCC2(x, y, z)
#define STATCC2(x, y, z) x ## y ## z

#ifdef STAT_PREFIX
 #define STATNAME(func) STATCC1(STAT_PREFIX, _, func)
#else
 #define STATNAME(func) func
#endif

/* global ROM tables */
#define CLIPTOSHORT                              STATNAME(CLIPTOSHORT)
#define LinearSRC_16bitProcessFrame              STATNAME(LinearSRC_16bitProcessFrame)
#define LinearSRC_32bitProcessFrame              STATNAME(LinearSRC_32bitProcessFrame)
#define LinearSRC_CheckDoSRC                     STATNAME(LinearSRC_CheckDoSRC)
#define LinearSRC_CheckUpdate                    STATNAME(LinearSRC_CheckUpdate)
#define LinearSRC_Create                         STATNAME(LinearSRC_Create)
#define LinearSRC_Destroy                        STATNAME(LinearSRC_Destroy)
#define LinearSRC_GetMaxOutputNum                STATNAME(LinearSRC_GetMaxOutputNum)
#define LinearSRC_ProcessFrame                   STATNAME(LinearSRC_ProcessFrame)
#define LinearSRC_SetSpeedAdjust                 STATNAME(LinearSRC_SetSpeedAdjust)
#define LinearSRC_UpdateChange                   STATNAME(LinearSRC_UpdateChange)
#define MLA16BB                                  STATNAME(MLA16BB)
#define MLA16BT                                  STATNAME(MLA16BT)
#define MLA16TB                                  STATNAME(MLA16TB)
#define MLA16TT                                  STATNAME(MLA16TT)
#define MLA32_16B                                STATNAME(MLA32_16B)
#define MLA32_16T                                STATNAME(MLA32_16T)
#define MULF32_16B                               STATNAME(MULF32_16B)
#define MULSHIFT32                               STATNAME(MULSHIFT32)
#define NEW_ResampleFlush                        STATNAME(NEW_ResampleFlush)
#define NEW_ResamplerCheck                       STATNAME(NEW_ResamplerCheck)
#define NEW_ResamplerCreate                      STATNAME(NEW_ResamplerCreate)
#define NEW_ResamplerFree                        STATNAME(NEW_ResamplerFree)
#define NEW_ResamplerGetMaxOutputNum             STATNAME(NEW_ResamplerGetMaxOutputNum)
#define NEW_ResamplerProcessFrame                STATNAME(NEW_ResamplerProcessFrame)
#define Resample2X_Flush                         STATNAME(Resample2X_Flush)
#define Resampler2X_Create                       STATNAME(Resampler2X_Create)
#define Resampler2X_Free                         STATNAME(Resampler2X_Free)
#define Resampler2X_GetMaxOutputNum              STATNAME(Resampler2X_GetMaxOutputNum)
#define Resampler2X_GetMinInputNum               STATNAME(Resampler2X_GetMinInputNum)
#define Resampler2X_Init                         STATNAME(Resampler2X_Init)
#define Resampler2X_Process                      STATNAME(Resampler2X_Process)
#define ResamplerMono1X1Process                  STATNAME(ResamplerMono1X1Process)
#define ResamplerMono1X2Process                  STATNAME(ResamplerMono1X2Process)
#define ResamplerMono1X4Process                  STATNAME(ResamplerMono1X4Process)
#define ResamplerMono1X6Process                  STATNAME(ResamplerMono1X6Process)
#define ResamplerMono2X1Process                  STATNAME(ResamplerMono2X1Process)
#define ResamplerMono4X1Process                  STATNAME(ResamplerMono4X1Process)
#define ResamplerMono6X1Process                  STATNAME(ResamplerMono6X1Process)
#define ResamplerStereo1X1Process                STATNAME(ResamplerStereo1X1Process)
#define ResamplerStereo1X2Process                STATNAME(ResamplerStereo1X2Process)
#define ResamplerStereo1X4Process                STATNAME(ResamplerStereo1X4Process)
#define ResamplerStereo1X6Process                STATNAME(ResamplerStereo1X6Process)
#define ResamplerStereo2X1Process                STATNAME(ResamplerStereo2X1Process)
#define ResamplerStereo4X1Process                STATNAME(ResamplerStereo4X1Process)
#define ResamplerStereo6X1Process                STATNAME(ResamplerStereo6X1Process)
#define ResamplerCheck                           STATNAME(ResamplerCheck)
#define ResamplerCreate                          STATNAME(ResamplerCreate)
#define ResamplerFree                            STATNAME(ResamplerFree)
#define RAInitResamplerRat                       STATNAME(RAInitResamplerRat)
#define ResampleConfig                           STATNAME(ResampleConfig)
#define ResampleFlush                            STATNAME(ResampleFlush)
#define ResamplerGetMaxOutputNum                 STATNAME(ResamplerGetMaxOutputNum)
#define ResamplerProcessFrame                    STATNAME(ResamplerProcessFrame)
#define ResamplerMonoProcess16                   STATNAME(ResamplerMonoProcess16)
#define ResamplerMonoProcess24                   STATNAME(ResamplerMonoProcess24)
#define ResamplerStereoProcess16                 STATNAME(ResamplerStereoProcess16)
#define ResamplerStereoProcess24                 STATNAME(ResamplerStereoProcess24)
#define SRCFracTable_Mono                        STATNAME(SRCFracTable_Mono)
#define SRCFracTable_Stereo                      STATNAME(SRCFracTable_Stereo)
#define VERSION                                  STATNAME(VERSION)
#define Volume_16bitProcessFrame                 STATNAME(Volume_16bitProcessFrame)
#define Volume_32itProcessFrame                  STATNAME(Volume_32itProcessFrame)
#define Volume_ProcessFrame                      STATNAME(Volume_ProcessFrame)
#define coef1x2                                  STATNAME(coef1x2)
#define coef1x2_low                              STATNAME(coef1x2_low)
#define coef1x2_mid                              STATNAME(coef1x2_mid)
#define coef1x4                                  STATNAME(coef1x4)
#define coef1x6                                  STATNAME(coef1x6)
#define coef2x1                                  STATNAME(coef2x1)
#define coef2x1_low                              STATNAME(coef2x1_low)
#define coef2x1_mid                              STATNAME(coef2x1_mid)
#define coef4x1                                  STATNAME(coef4x1)
#define coef6x1                                  STATNAME(coef6x1)
#define cvt2int                                  STATNAME(cvt2int)
#define cvtShortShort                            STATNAME(cvtShortShort)
#define frame_dummy                              STATNAME(frame_dummy)
#define g_s32IvtSfTab                            STATNAME(g_s32IvtSfTab)
#define g_s32SampleRateTab                       STATNAME(g_s32SampleRateTab)
#define gcd                                      STATNAME(gcd)
#define res_11_12_good_filttab                   STATNAME(res_11_12_good_filttab)
#define res_11_12_good_nextphasetab              STATNAME(res_11_12_good_nextphasetab)
#define res_11_12_mid_filttab                    STATNAME(res_11_12_mid_filttab)
#define res_11_16_good_nextphasetab              STATNAME(res_11_16_good_nextphasetab)
#define res_11_16_mid_filttab                    STATNAME(res_11_16_mid_filttab)
#define res_11_24_good_nextphasetab              STATNAME(res_11_24_good_nextphasetab)
#define res_11_24_mid_filttab                    STATNAME(res_11_24_mid_filttab)
#define res_11_32_good_nextphasetab              STATNAME(res_11_32_good_nextphasetab)
#define res_11_32_mid_filttab                    STATNAME(res_11_32_mid_filttab)
#define res_11_48_good_nextphasetab              STATNAME(res_11_48_good_nextphasetab)
#define res_11_48_mid_filttab                    STATNAME(res_11_48_mid_filttab)
#define res_12_16_good_filttab                   STATNAME(res_12_16_good_filttab)
#define res_12_16_good_nextphasetab              STATNAME(res_12_16_good_nextphasetab)
#define res_12_22_good_nextphasetab              STATNAME(res_12_22_good_nextphasetab)
#define res_12_22_mid_filttab                    STATNAME(res_12_22_mid_filttab)
#define res_12_32_good_filttab                   STATNAME(res_12_32_good_filttab)
#define res_12_32_good_nextphasetab              STATNAME(res_12_32_good_nextphasetab)
#define res_12_44_good_nextphasetab              STATNAME(res_12_44_good_nextphasetab)
#define res_12_44_mid_filttab                    STATNAME(res_12_44_mid_filttab)
#define res_32_48_mid_filttab                    STATNAME(res_32_48_mid_filttab)
#define res_32_48_mid_nextphasetab               STATNAME(res_32_48_mid_nextphasetab)
#define res_44_48_mid_filttab                    STATNAME(res_44_48_mid_filttab)
#define res_44_48_mid_nextphasetab               STATNAME(res_44_48_mid_nextphasetab)
#define res_48_48_good_filttab                   STATNAME(res_48_48_good_filttab)
#define res_48_48_nextphasetab                   STATNAME(res_48_48_nextphasetab)
#define res_8_11_good_filttab                    STATNAME(res_8_11_good_filttab)
#define res_8_11_good_nextphasetab               STATNAME(res_8_11_good_nextphasetab)
#define res_8_11_mid_filttab                     STATNAME(res_8_11_mid_filttab)
#define res_8_12_good_filttab                    STATNAME(res_8_12_good_filttab)
#define res_8_12_good_nextphasetab               STATNAME(res_8_12_good_nextphasetab)
#define res_8_16_good_filttab                    STATNAME(res_8_16_good_filttab)
#define res_8_16_good_nextphasetab               STATNAME(res_8_16_good_nextphasetab)
#define res_8_22_good_nextphasetab               STATNAME(res_8_22_good_nextphasetab)
#define res_8_22_mid_filttab                     STATNAME(res_8_22_mid_filttab)
#define res_8_24_good_filttab                    STATNAME(res_8_24_good_filttab)
#define res_8_24_good_nextphasetab               STATNAME(res_8_24_good_nextphasetab)
#define res_8_32_good_filttab                    STATNAME(res_8_32_good_filttab)
#define res_8_32_good_nextphasetab               STATNAME(res_8_32_good_nextphasetab)
#define res_8_44_good_nextphasetab               STATNAME(res_8_44_good_nextphasetab)
#define res_8_44_mid_filttab                     STATNAME(res_8_44_mid_filttab)
#define res_8_48_good_filttab                    STATNAME(res_8_48_good_filttab)
#define res_8_48_good_nextphasetab               STATNAME(res_8_48_good_nextphasetab)
#define res_32_48_low_nextphasetab               STATNAME(res_32_48_low_nextphasetab)
#define res_32_48_low_filttab                    STATNAME(res_32_48_low_filttab)
#define res_44_48_low_nextphasetab               STATNAME(res_44_48_low_nextphasetab)
#define res_44_48_low_filttab                    STATNAME(res_44_48_low_filttab)
#define res_11_44_good_nextphasetab              STATNAME(res_11_44_good_nextphasetab)
#define res_11_44_good_filttab                   STATNAME(res_11_44_good_filttab)
#define resample_mono_proc_list                  STATNAME(resample_mono_proc_list)
#define resample_stero_proc_list                 STATNAME(resample_stero_proc_list)
#define resampler_info                           STATNAME(resampler_info)
#define resampler_nwing                          STATNAME(resampler_nwing)
#define shift                                    STATNAME(shift)
#define x5_filter_nobypass                       STATNAME(x5_filter_nobypass)

#endif /* _RESAMPLE_STATNAME_H */
