#ADD PLATFORM MACRO HERE
ifeq ($(strip $(WITH_HI3798CV2X_PLATFORM)), true)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DWITH_HI3798CV2X_PLATFORM
endif

TRUSTEDCORE_DEVCHIP_CFLAGS += -fno-short-enums -fstack-protector-all -Wstack-protector

TRUSTEDCORE_DEVCHIP_CFLAGS += -DCHIP_TYPE_$(HI_CHIP_TYPE)

ifeq ($(WITH_NEON_SUPPORT) , true)
TRUSTEDCORE_DEVCHIP_CFLAGS += -mfloat-abi=softfp -mfpu=neon
TRUSTEDCORE_DEVCHIP_CFLAGS += -DCONFIG_NEON_SUPPORT
endif

include $(TRUSTEDCORE_DIR)/platform/${PLATFORM_DIR}/${PLATFORM_DIR_NAME}/module_list.mak

ifeq ($(strip $(WITH_CLEAR_BOOT)), true)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DWITH_CLEAR_BOOT
endif

ifeq ($(strip $(WITH_ARMV8_SUPPORT)), true)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DWITH_ARMV8_SUPPORT
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DATF_MEM_SIZE=$(ATF_MEM_SIZE)
endif

ifeq ($(strip $(TRUSTEDCORE_LARGER_MEM)), true)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DTRUSTEDCORE_LARGER_MEM
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DTRUSTEDCORE_SHAREMEM_SIZE=$(TRUSTEDCORE_SHAREMEM_SIZE)
endif

ifeq ($(strip $(WITH_TUI_SUPPORT)), true)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DTEE_SUPPORT_TUI
endif

ifeq ($(strip $(TRUSTEDCORE_FINGERPRINT)), true)
TRUSTEDCORE_DEVCHIP_CFLAGS  += -DTEE_FINGERPRINT
endif

TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_RAM_TOTAL_AMOUNT=$(TRUSTEDCORE_RAM_TOTAL_AMOUNT)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_RAM_ORDER=$(TRUSTEDCORE_RAM_ORDER)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_SEC_MMZ_MEM_SIZE=$(TRUSTEDCORE_SEC_MMZ_MEM_SIZE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_SEC_SMMU_PAGETABLE_SIZE=$(TRUSTEDCORE_SEC_SMMU_PAGETABLE_SIZE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_TA_RUN_MEM_SIZE=$(TRUSTEDCORE_TA_RUN_MEM_SIZE)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DTRUSTEDCORE_TA_SHARE_MEM_SIZE=$(TRUSTEDCORE_TA_SHARE_MEM_SIZE)

ifeq ($(strip $(WITH_GP_V1_1_SUPPORTED)), true)
$(info --- GP_V1_1_SUPPORTED ---)
TRUSTEDCORE_DEVCHIP_CFLAGS += -DGP_V1_1_SUPPORTED
endif

TRUSTEDCORE_DEVCHIP_ASFLAGS += $(TRUSTEDCORE_DEVCHIP_CFLAGS)

$(info TRUSTEDCORE_DEVCHIP_CFLAGS=$(TRUSTEDCORE_DEVCHIP_CFLAGS))

#################################################
# packing config
#################################################
#disable by default 
SUPPORT_TEST_TA := 0
SUPPORT_SEC_MMZ := 0
SUPPORT_VFMW := 0
SUPPORT_SMMU := 0
SUPPORT_HISI_TEST :=0
SUPPORT_DMX := 0
SUPPORT_PVR := 0
SUPPORT_HDMI := 0
SUPPORT_WIDEVINE := 0
SUPPORT_PLAYREADY := 0
SUPPORT_HISI_DEMO := 0
SUPPORT_HISI_VDP :=0
SUPPORT_VMX_ULTRA := 0
SUPPORT_VMX_ULTRA_VMXTAC_TEST := 0
SUPPORT_VMX_ULTRA_ITAC_TEST := 0
SUPPORT_VPSS := 0
SUPPORT_HISI_DRM := 0

ifeq ($(strip $(WITH_TEST_TA)), true)
SUPPORT_TEST_TA := 1
endif

#get config form platform.mk
ifeq ($(strip $(WITH_HISI_SEC_MMZ)), true)
SUPPORT_SEC_MMZ := 1
endif

ifeq ($(strip $(WITH_HISI_VFMW)), true)
SUPPORT_VFMW := 1
endif

ifeq ($(strip $(WITH_HISI_SMMU)), true)
SUPPORT_SMMU := 1
endif

ifeq ($(strip $(WITH_HISI_TEST)), true)
SUPPORT_HISI_TEST :=1
endif

ifeq ($(strip $(WITH_HISI_DMX)), true)
SUPPORT_DMX := 1
endif

ifeq ($(strip $(WITH_HISI_PVR)), true)
SUPPORT_PVR := 1
endif

ifeq ($(strip $(WITH_HISI_SEC_HDMI)), true)
SUPPORT_HDMI := 1
endif

ifeq ($(strip $(WITH_HISI_WIDEVINE)), true)
SUPPORT_WIDEVINE := 1
endif

ifeq ($(strip $(WITH_HISI_PLAYREADY)), true)
SUPPORT_PLAYREADY := 1
endif

ifeq ($(strip $(WITH_HISI_DEMO)), true)
SUPPORT_HISI_DEMO := 1
endif

ifeq ($(strip $(WITH_HISI_VDP)), true)
SUPPORT_HISI_VDP := 1
endif

ifeq ($(strip $(WITH_COMPONENT_VMX_ULTRA)), true)
SUPPORT_VMX_ULTRA := 1
endif

ifeq ($(strip $(WITH_COMPONENT_VMX_ULTRA_VMXTAC_TEST)), true)
SUPPORT_VMX_ULTRA_VMXTAC_TEST := 1
endif
ifeq ($(strip $(WITH_COMPONENT_VMX_ULTRA_ITAC_TEST)), true)
SUPPORT_VMX_ULTRA_ITAC_TEST := 1
endif

ifeq ($(strip $(WITH_HISI_VPSS)), true)
SUPPORT_VPSS := 1
endif

ifeq ($(strip $(WITH_HISI_DRM)), true)
SUPPORT_HISI_DRM := 1
endif

ifeq ($(strip $(WITH_HISI_AVPLAY)), true)
SUPPORT_AVPLAY := 1
endif

PACKING_CFG = \
	"$(TRUSTEDCORE_TEXT_BASE)" \
	"$(PLATFORM_DIR_NAME)" \
	"$(OUT)" \
	"$(SUPPORT_TEST_TA)" \
	"$(SUPPORT_SEC_MMZ)" \
	"$(SUPPORT_VFMW)" \
	"$(SUPPORT_SMMU)" \
	"$(SUPPORT_HISI_TEST)" \
	"$(SUPPORT_DMX)" \
	"$(SUPPORT_PVR)" \
	"$(SUPPORT_HDMI)" \
	"$(SUPPORT_WIDEVINE)" \
	"$(SUPPORT_HISI_DEMO)" \
	"$(SUPPORT_HISI_VDP)" \
	"$(SUPPORT_VMX_ULTRA)" \
	"$(SUPPORT_VMX_ULTRA_VMXTAC_TEST)" \
	"$(SUPPORT_VMX_ULTRA_ITAC_TEST)" \
	"$(SUPPORT_VPSS)" \
	"$(SUPPORT_HISI_DRM)" \
	"$(SUPPORT_PLAYREADY)" \
	"$(SUPPORT_AVPLAY)"
