#ifndef __HAL_TNR_H__
#define __HAL_TNR_H__
#if EDA_TEST
#include <stdio.h>
#include <stdlib.h>
#include <vdp_assert.h>
#endif

#if VDP_C_COMPILE
#endif

#include "vdp_define.h"

//////TNR
HI_VOID VDP_VID_SetTnrRefReqCtrl                    (HI_U32 u32Data, HI_U32 u32Data1);
HI_VOID VDP_VID_SetTnrMadDbmReqCtrl                 (HI_U32 u32Data, HI_U32 u32Data1);
HI_VOID VDP_VID_SetTnrRefDataWidth                  (HI_U32 u32Data, HI_U32 u32Data1);
HI_VOID VDP_VID_SetTNRPgbmEnable                    (HI_U32 u32Data, HI_U32 u32Data1);
HI_VOID VDP_VID_SetTnrEnable                        (HI_U32 u32Data,HI_U32 tnr_en);
HI_VOID VDP_VID_SetTNRTmLpfMode                     (HI_U32 u32Data,HI_U32 tm_lpf_mode);
HI_VOID VDP_VID_SetTNRTeYCLpfMode                   (HI_U32 u32Data,HI_U32 te_ylpf_mode, HI_U32 te_clpf_mode);
HI_VOID VDP_VID_SetTNRTmYCMtMeanMode                (HI_U32 u32Data,HI_U32 tm_ymt_mean_mode, HI_U32 tm_cmt_mean_mode);
HI_VOID VDP_VID_SetTNRTmYCMtMode                    (HI_U32 u32Data,HI_U32 tm_ymt_mode, HI_U32 tm_cmt_mode);
HI_VOID VDP_VID_SetTNRTeYCEgMeanMode                (HI_U32 u32Data,HI_U32 te_yeg_mean_mode, HI_U32 te_ceg_mean_mode);
HI_VOID VDP_VID_SetTNRTeYCEgMode                    (HI_U32 u32Data,HI_U32 te_yceg_mode);
HI_VOID VDP_VID_SetTNRTfmLpfEnable                  (HI_U32 u32Data,HI_U32 tfm_lpf_en);
HI_VOID VDP_VID_SetTNREdgeYCMovingLpfMode           (HI_U32 u32Data,HI_U32 edge_ymoving_lpfmode, HI_U32 edge_cmoving_lpfmode);
HI_VOID VDP_VID_SetTNRHistMotionEnable              (HI_U32 u32Data,HI_U32 hist_motion_en);
HI_VOID VDP_VID_SetTNRYCBypass                      (HI_U32 u32Data,HI_U32 tnr_y_bypass, HI_U32 tnr_c_bypass);
HI_VOID VDP_VID_SetTNRMarketMode                    (HI_U32 u32Data,HI_U32 market_mode);
HI_VOID VDP_VID_SetTNRMarketEnable                  (HI_U32 u32Data,HI_U32 market_en);
HI_VOID VDP_VID_SetTNRTmYMtMeanRatioEnable          (HI_U32 u32Data,HI_U32 tm_ymt_meanratio_en);
HI_VOID VDP_VID_SetTNRTmYMtMapping                  (HI_U32 u32Data,HI_U32 tm_ymt_mapping_min, HI_U32 tm_ymt_mapping_max);
HI_VOID VDP_VID_SetTNRTmYMtMappingR                 (HI_U32 u32Data,HI_U32 tm_ymt_mapping_r0, HI_U32 tm_ymt_mapping_r1, HI_U32 tm_ymt_mapping_r2, HI_U32 tm_ymt_mapping_r3, HI_U32 tm_ymt_mapping_r4);
HI_VOID VDP_VID_SetTNRTmYMtMappingT                 (HI_U32 u32Data,HI_U32 tm_ymt_mapping_t1, HI_U32 tm_ymt_mapping_t2, HI_U32 tm_ymt_mapping_t3, HI_U32 tm_ymt_mapping_t4, HI_U32 tm_ymt_mapping_t5, HI_U32 tm_ymt_mapping_t6);
HI_VOID VDP_VID_SetTNRTmYMtMappingK                 (HI_U32 u32Data,HI_S32 tm_ymt_mapping_k1, HI_S32 tm_ymt_mapping_k2, HI_S32 tm_ymt_mapping_k3, HI_S32 tm_ymt_mapping_k4);
HI_VOID VDP_VID_SetTNRTmCMtMeanRatioEnable          (HI_U32 u32Data,HI_U32 tm_cmt_meanratio_en);
HI_VOID VDP_VID_SetTNRTmCMtMapping                  (HI_U32 u32Data,HI_U32 tm_cmt_mapping_min, HI_U32 tm_cmt_mapping_max);
HI_VOID VDP_VID_SetTNRTmCMtMappingR                 (HI_U32 u32Data,HI_U32 tm_cmt_mapping_r0, HI_U32 tm_cmt_mapping_r1, HI_U32 tm_cmt_mapping_r2, HI_U32 tm_cmt_mapping_r3, HI_U32 tm_cmt_mapping_r4);
HI_VOID VDP_VID_SetTNRTmCMtMappingT                 (HI_U32 u32Data,HI_U32 tm_cmt_mapping_t1, HI_U32 tm_cmt_mapping_t2, HI_U32 tm_cmt_mapping_t3, HI_U32 tm_cmt_mapping_t4, HI_U32 tm_cmt_mapping_t5, HI_U32 tm_cmt_mapping_t6);
HI_VOID VDP_VID_SetTNRTmCMtMappingK                 (HI_U32 u32Data,HI_S32 tm_cmt_mapping_k1, HI_S32 tm_cmt_mapping_k2, HI_S32 tm_cmt_mapping_k3, HI_S32 tm_cmt_mapping_k4);
HI_VOID VDP_VID_SetTNRTmYMtMeanRatio                (HI_U32 u32Data,HI_U32 tm_ymt_meanratio_min, HI_U32 tm_ymt_meanratio_max);
HI_VOID VDP_VID_SetTNRTmYMtMeanRatioR               (HI_U32 u32Data,HI_U32 tm_ymt_meanratio_r0, HI_U32 tm_ymt_meanratio_r1, HI_U32 tm_ymt_meanratio_r2, HI_U32 tm_ymt_meanratio_r3, HI_U32 tm_ymt_meanratio_r4);
HI_VOID VDP_VID_SetTNRTmYMtMeanRatioT               (HI_U32 u32Data,HI_U32 tm_ymt_meanratio_t1, HI_U32 tm_ymt_meanratio_t2, HI_U32 tm_ymt_meanratio_t3, HI_U32 tm_ymt_meanratio_t4, HI_U32 tm_ymt_meanratio_t5, HI_U32 tm_ymt_meanratio_t6);
HI_VOID VDP_VID_SetTNRTmYMeanRatioK                 (HI_U32 u32Data,HI_S32 tm_ymt_meanratio_k1, HI_S32 tm_ymt_meanratio_k2, HI_S32 tm_ymt_meanratio_k3, HI_S32 tm_ymt_meanratio_k4);
HI_VOID VDP_VID_SetTNRTmCMtMeanRatio                (HI_U32 u32Data,HI_U32 tm_cmt_meanratio_min, HI_U32 tm_cmt_meanratio_max);
HI_VOID VDP_VID_SetTNRTmCMtMeanRatioR               (HI_U32 u32Data,HI_U32 tm_cmt_meanratio_r0, HI_U32 tm_cmt_meanratio_r1, HI_U32 tm_cmt_meanratio_r2, HI_U32 tm_cmt_meanratio_r3, HI_U32 tm_cmt_meanratio_r4);
HI_VOID VDP_VID_SetTNRTmCMtMeanRatioT               (HI_U32 u32Data,HI_U32 tm_cmt_meanratio_t1, HI_U32 tm_cmt_meanratio_t2, HI_U32 tm_cmt_meanratio_t3, HI_U32 tm_cmt_meanratio_t4, HI_U32 tm_cmt_meanratio_t5, HI_U32 tm_cmt_meanratio_t6);
HI_VOID VDP_VID_SetTNRTmCMeanRatioK                 (HI_U32 u32Data,HI_S32 tm_cmt_meanratio_k1, HI_S32 tm_cmt_meanratio_k2, HI_S32 tm_cmt_meanratio_k3, HI_S32 tm_cmt_meanratio_k4);
HI_VOID VDP_VID_SetTNRTmYCMtCoef                    (HI_U32 u32Data,HI_U32 tm_ycmtcoef0, HI_U32 tm_ycmtcoef1, HI_U32 tm_ycmtcoef2, HI_U32 tm_ycmtcoef3, HI_U32 tm_ycmtcoef4);
HI_VOID VDP_VID_SetTNRTmYCLpfCoef                   (HI_U32 u32Data,HI_U32 tm_yclpfcoef0, HI_U32 tm_yclpfcoef1, HI_U32 tm_yclpfcoef2, HI_U32 tm_yclpfcoef3, HI_U32 tm_yclpfcoef4);
HI_VOID VDP_VID_SetTNRTeYHpf1Coef                   (HI_U32 u32Data,HI_S32 te_yhpf1coef0, HI_S32 te_yhpf1coef1, HI_S32 te_yhpf1coef2, HI_S32 te_yhpf1coef3, HI_S32 te_yhpf1coef4, HI_S32 te_yhpf1coef5, HI_S32 te_yhpf1coef6, HI_S32 te_yhpf1coef7, HI_S32 te_yhpf1coef8, HI_U32 te_yhpf1lshiift);
HI_VOID VDP_VID_SetTNRTeYHpf2Coef                   (HI_U32 u32Data,HI_S32 te_yhpf2coef0, HI_S32 te_yhpf2coef1, HI_S32 te_yhpf2coef2, HI_S32 te_yhpf2coef3, HI_S32 te_yhpf2coef4, HI_S32 te_yhpf2coef5, HI_S32 te_yhpf2coef6, HI_S32 te_yhpf2coef7, HI_S32 te_yhpf2coef8, HI_U32 te_yhpf2lshiift);
HI_VOID VDP_VID_SetTNRTeYHpf3Coef                   (HI_U32 u32Data,HI_S32 te_yhpf3coef0, HI_S32 te_yhpf3coef1, HI_S32 te_yhpf3coef2, HI_S32 te_yhpf3coef3, HI_S32 te_yhpf3coef4, HI_S32 te_yhpf3coef5, HI_S32 te_yhpf3coef6, HI_S32 te_yhpf3coef7, HI_S32 te_yhpf3coef8, HI_U32 te_yhpf3lshiift);
HI_VOID VDP_VID_SetTNRTeYHpf4Coef                   (HI_U32 u32Data,HI_S32 te_yhpf4coef0, HI_S32 te_yhpf4coef1, HI_S32 te_yhpf4coef2, HI_S32 te_yhpf4coef3, HI_S32 te_yhpf4coef4, HI_S32 te_yhpf4coef5, HI_S32 te_yhpf4coef6, HI_S32 te_yhpf4coef7, HI_S32 te_yhpf4coef8, HI_U32 te_yhpf4lshiift);
HI_VOID VDP_VID_SetTNRTeYMtMeanLpfCoef              (HI_U32 u32Data,HI_U32 te_ymtmeanlpfcoef0, HI_U32 te_ymtmeanlpfcoef1, HI_U32 te_ymtmeanlpfcoef2, HI_U32 te_ymtmeanlpfcoef3, HI_U32 te_ymtmeanlpfcoef4, HI_U32 te_ymtmeanlpfcoef5, HI_U32 te_ymtmeanlpfcoef6, HI_U32 te_ymtmeanlpfcoef7, HI_U32 te_ymtmeanlpfcoef8);
HI_VOID VDP_VID_SetTNRTeYCEgMeanRatioEnable         (HI_U32 u32Data,HI_U32 te_yceg_meanratio_en);
HI_VOID VDP_VID_SetTNRTeYCEgMeanRatio               (HI_U32 u32Data,HI_U32 te_yceg_meanratio_min, HI_U32 te_yceg_meanratio_max);
HI_VOID VDP_VID_SetTNRTeYCEgMeanRatioR              (HI_U32 u32Data,HI_U32 te_yceg_meanratio_r0, HI_U32 te_yceg_meanratio_r1, HI_U32 te_yceg_meanratio_r2, HI_U32 te_yceg_meanratio_r3, HI_U32 te_yceg_meanratio_r4);
HI_VOID VDP_VID_SetTNRTeYCEgMeanRatioT              (HI_U32 u32Data,HI_U32 te_yceg_meanratio_t1, HI_U32 te_yceg_meanratio_t2, HI_U32 te_yceg_meanratio_t3, HI_U32 te_yceg_meanratio_t4, HI_U32 te_yceg_meanratio_t5, HI_U32 te_yceg_meanratio_t6);
HI_VOID VDP_VID_SetTNRTeYCEgMeanRatioK              (HI_U32 u32Data,HI_S32 te_yceg_meanratio_k1, HI_S32 te_yceg_meanratio_k2, HI_S32 te_yceg_meanratio_k3, HI_S32 te_yceg_meanratio_k4);
HI_VOID VDP_VID_SetTNRTeCMtMeanRatioEnable          (HI_U32 u32Data,HI_U32 te_ycmt_meanratio_en);
HI_VOID VDP_VID_SetTNRTeCMtMeanRatio                (HI_U32 u32Data,HI_U32 te_ycmt_meanratio_min, HI_U32 te_ycmt_meanratio_max);
HI_VOID VDP_VID_SetTNRTeCMtMeanRatioR               (HI_U32 u32Data,HI_U32 te_ycmt_meanratio_r0, HI_U32 te_ycmt_meanratio_r1, HI_U32 te_ycmt_meanratio_r2, HI_U32 te_ycmt_meanratio_r3, HI_U32 te_ycmt_meanratio_r4);
HI_VOID VDP_VID_SetTNRTeCMtMeanRatioT               (HI_U32 u32Data,HI_U32 te_ycmt_meanratio_t1, HI_U32 te_ycmt_meanratio_t2, HI_U32 te_ycmt_meanratio_t3, HI_U32 te_ycmt_meanratio_t4, HI_U32 te_ycmt_meanratio_t5, HI_U32 te_ycmt_meanratio_t6);
HI_VOID VDP_VID_SetTNRTeCMtMeanRatioK               (HI_U32 u32Data,HI_S32 te_ycmt_meanratio_k1, HI_S32 te_ycmt_meanratio_k2, HI_S32 te_ycmt_meanratio_k3, HI_S32 te_ycmt_meanratio_k4);
//HI_VOID VDP_VID_SetTNRTeYMtMeanRatioEnable        (HI_U32 u32Data,HI_U32 te_ycmt_meanmtratio_en);
//HI_VOID VDP_VID_SetTNRTeYMtMeanRatio              (HI_U32 u32Data,HI_U32 te_ycmt_meanmtratio_min, HI_U32 te_ycmt_meanmtratio_max);
//HI_VOID VDP_VID_SetTNRTeYMtMeanRatioR             (HI_U32 u32Data,HI_U32 te_ycmt_meanmtratio_r0, HI_U32 te_ycmt_meanmtratio_r1, HI_U32 te_ycmt_meanmtratio_r2, HI_U32 te_ycmt_meanmtratio_r3, HI_U32 te_ycmt_meanmtratio_r4);
//HI_VOID VDP_VID_SetTNRTeYMtMeanRatioT             (HI_U32 u32Data,HI_U32 te_ycmt_meanmtratio_t1, HI_U32 te_ycmt_meanmtratio_t2, HI_U32 te_ycmt_meanmtratio_t3, HI_U32 te_ycmt_meanmtratio_t4, HI_U32 te_ycmt_meanmtratio_t5, HI_U32 te_ycmt_meanmtratio_t6);
//HI_VOID VDP_VID_SetTNRTeYMtMeanRatioK             (HI_U32 u32Data,HI_U32 te_ycmt_meanmtratio_k1, HI_U32 te_ycmt_meanmtratio_k2, HI_U32 te_ycmt_meanmtratio_k3, HI_U32 te_ycmt_meanmtratio_k4);
HI_VOID VDP_VID_SetTNRTeYCMtMapping                 (HI_U32 u32Data,HI_U32 te_ycmt_mapping_min, HI_U32 te_ycmt_mapping_max);
HI_VOID VDP_VID_SetTNRTeYCMtMappingR                (HI_U32 u32Data,HI_U32 te_ycmt_mapping_r0, HI_U32 te_ycmt_mapping_r1, HI_U32 te_ycmt_mapping_r2, HI_U32 te_ycmt_mapping_r3, HI_U32 te_ycmt_mapping_r4);
HI_VOID VDP_VID_SetTNRTeYCMtMappingT                (HI_U32 u32Data,HI_U32 te_ycmt_mapping_t1, HI_U32 te_ycmt_mapping_t2, HI_U32 te_ycmt_mapping_t3, HI_U32 te_ycmt_mapping_t4, HI_U32 te_ycmt_mapping_t5, HI_U32 te_ycmt_mapping_t6);
HI_VOID VDP_VID_SetTNRTeYCMtMappingK                (HI_U32 u32Data,HI_S32 te_ycmt_mapping_k1, HI_S32 te_ycmt_mapping_k2, HI_S32 te_ycmt_mapping_k3, HI_S32 te_ycmt_mapping_k4);
HI_VOID VDP_VID_SetTNRTeYCEgMapping                 (HI_U32 u32Data,HI_U32 te_yceg_mapping_min, HI_U32 te_yceg_mapping_max);
HI_VOID VDP_VID_SetTNRTeYCEgMappingR                (HI_U32 u32Data,HI_U32 te_yceg_mapping_r0, HI_U32 te_yceg_mapping_r1, HI_U32 te_yceg_mapping_r2, HI_U32 te_yceg_mapping_r3, HI_U32 te_yceg_mapping_r4);
HI_VOID VDP_VID_SetTNRTeYCEgMappingT                (HI_U32 u32Data,HI_U32 te_yceg_mapping_t1, HI_U32 te_yceg_mapping_t2, HI_U32 te_yceg_mapping_t3, HI_U32 te_yceg_mapping_t4, HI_U32 te_yceg_mapping_t5, HI_U32 te_yceg_mapping_t6);
HI_VOID VDP_VID_SetTNRTeYCEgMappingK                (HI_U32 u32Data,HI_S32 te_yceg_mapping_k1, HI_S32 te_yceg_mapping_k2, HI_S32 te_yceg_mapping_k3, HI_S32 te_yceg_mapping_k4);
HI_VOID VDP_VID_SetTNRTeCEgCK                       (HI_U32 u32Data,HI_S32 te_ceg_core, HI_U32 te_ceg_k, HI_U32 te_crshift);
HI_VOID VDP_VID_SetTNRTeCEgCK2                      (HI_U32 u32Data,HI_S32 te_ceg_core2, HI_U32 te_ceg_k2);
HI_VOID VDP_VID_SetTNRTeCMtCK1                      (HI_U32 u32Data,HI_S32 te_cmt_core1, HI_U32 te_cmt_k1);
HI_VOID VDP_VID_SetTNRTeCMtCK2                      (HI_U32 u32Data,HI_S32 te_cmt_core2, HI_U32 te_cmt_k2);
HI_VOID VDP_VID_SetTNRTeCMtCK3                      (HI_U32 u32Data,HI_S32 te_cmt_core3, HI_U32 te_cmt_k3);
HI_VOID VDP_VID_SetTNRTeCHpf4Coef                   (HI_U32 u32Data,HI_S32 te_chpf4coef0, HI_S32 te_chpf4coef1, HI_S32 te_chpf4coef2, HI_S32 te_chpf4coef3, HI_S32 te_chpf4coef4, HI_S32 te_chpf4coef5, HI_S32 te_chpf4coef6, HI_S32 te_chpf4coef7, HI_S32 te_chpf4coef8, HI_U32 te_chpf4lshiift);
HI_VOID VDP_VID_SetTNRTeYEgWeight                   (HI_U32 u32Data,HI_U32 te_yeg_weight1, HI_U32 te_yeg_weight2, HI_U32 te_yeg_weight3, HI_U32 te_yeg_weight4);
HI_VOID VDP_VID_SetTNRTeCEgWeight                   (HI_U32 u32Data,HI_U32 te_ceg_weight1, HI_U32 te_ceg_weight2, HI_U32 te_ceg_weight3, HI_U32 te_ceg_weight4);
HI_VOID VDP_VID_SetTNRTeCMeanLpfCoef                (HI_U32 u32Data,HI_U32 te_cmean_lpfcoef0, HI_U32 te_cmean_lpfcoef1, HI_U32 te_cmean_lpfcoef2, HI_U32 te_cmean_lpfcoef3, HI_U32 te_cmean_lpfcoef4, HI_U32 te_cmean_lpfcoef5, HI_U32 te_cmean_lpfcoef6, HI_U32 te_cmean_lpfcoef7, HI_U32 te_cmean_lpfcoef8);
HI_VOID VDP_VID_SetTNRTeYMtCK1                      (HI_U32 u32Data,HI_S32 te_ymt_core1, HI_U32 te_ymt_k1);
HI_VOID VDP_VID_SetTNRTeYMtCK2                      (HI_U32 u32Data,HI_S32 te_ymt_core2, HI_U32 te_ymt_k2);
HI_VOID VDP_VID_SetTNRTeYEgCK1                      (HI_U32 u32Data,HI_S32 te_yeg_core1, HI_U32 te_yeg_k1);
HI_VOID VDP_VID_SetTNRTeYMtCK                       (HI_U32 u32Data,HI_S32 te_ymt_core, HI_U32 te_ymt_k);
HI_VOID VDP_VID_SetTNRTeYEgCK                       (HI_U32 u32Data,HI_S32 te_yeg_core, HI_U32 te_yeg_k);
HI_VOID VDP_VID_SetTNRTeYRShift                     (HI_U32 u32Data,HI_U32 te_yrshift);
HI_VOID VDP_VID_SetTNRTeYMovingCK                   (HI_U32 u32Data,HI_S32 te_ymoving_core, HI_U32 te_ymoving_k);
HI_VOID VDP_VID_SetTNRTfmCMotionCK                  (HI_U32 u32Data,HI_S32 tfm_cmotion_core, HI_U32 tfm_cmotion_k);
HI_VOID VDP_VID_SetTNRTfmCEdgeCK                    (HI_U32 u32Data,HI_S32 tfm_cedge_core, HI_U32 tfm_cedge_k);
HI_VOID VDP_VID_SetTNRTfm2DUpdate                   (HI_U32 u32Data,HI_U32 tfm_2dupdate);
HI_VOID VDP_VID_SetTNRTfmCbCrUpdate                 (HI_U32 u32Data,HI_U32 tfm_cbcrupdate);
HI_VOID VDP_VID_SetTNRTfmYMapping                   (HI_U32 u32Data,HI_U32 tfm_y_mapping_min, HI_U32 tfm_y_mapping_max);
HI_VOID VDP_VID_SetTNRTfmYMappingR                  (HI_U32 u32Data,HI_U32 tfm_y_mapping_r0, HI_U32 tfm_y_mapping_r1, HI_U32 tfm_y_mapping_r2, HI_U32 tfm_y_mapping_r3, HI_U32 tfm_y_mapping_r4);
HI_VOID VDP_VID_SetTNRTfmYMappingT                  (HI_U32 u32Data,HI_U32 tfm_y_mapping_t1, HI_U32 tfm_y_mapping_t2, HI_U32 tfm_y_mapping_t3, HI_U32 tfm_y_mapping_t4, HI_U32 tfm_y_mapping_t5, HI_U32 tfm_y_mapping_t6);
HI_VOID VDP_VID_SetTNRTfmYMappingK                  (HI_U32 u32Data,HI_S32 tfm_y_mapping_k1, HI_S32 tfm_y_mapping_k2, HI_S32 tfm_y_mapping_k3, HI_S32 tfm_y_mapping_k4);
HI_VOID VDP_VID_SetTNRTfmCMapping                   (HI_U32 u32Data,HI_U32 tfm_c_mapping_min, HI_U32 tfm_c_mapping_max);
HI_VOID VDP_VID_SetTNRTfmCMappingR                  (HI_U32 u32Data,HI_U32 tfm_c_mapping_r0, HI_U32 tfm_c_mapping_r1, HI_U32 tfm_c_mapping_r2, HI_U32 tfm_c_mapping_r3, HI_U32 tfm_c_mapping_r4);
HI_VOID VDP_VID_SetTNRTfmCMappingT                  (HI_U32 u32Data,HI_U32 tfm_c_mapping_t1, HI_U32 tfm_c_mapping_t2, HI_U32 tfm_c_mapping_t3, HI_U32 tfm_c_mapping_t4, HI_U32 tfm_c_mapping_t5, HI_U32 tfm_c_mapping_t6);
HI_VOID VDP_VID_SetTNRTfmCMappingK                  (HI_U32 u32Data,HI_S32 tfm_c_mapping_k1, HI_S32 tfm_c_mapping_k2, HI_S32 tfm_c_mapping_k3, HI_S32 tfm_c_mapping_k4);
HI_VOID VDP_VID_SetTNRTfmHismTerm                   (HI_U32 u32Data,HI_U32 tfm_hism_term1, HI_U32 tfm_hism_term2);
HI_VOID VDP_VID_SetTNRTfmHismAlpha                  (HI_U32 u32Data,HI_U32 tfm_hism_alpha1, HI_U32 tfm_hism_alpha2);
HI_VOID VDP_VID_SetTNRTfmFilterMode                 (HI_U32 u32Data,HI_U32 tfm_filter_mode);
HI_VOID VDP_VID_SetTNRTfmCalcMode                   (HI_U32 u32Data,HI_U32 tfm_calc_mode);
HI_VOID VDP_VID_SetTNRTfmSceneChangeEnable          (HI_U32 u32Data,HI_U32 tfm_scenechange_en);
HI_VOID VDP_VID_SetTNRTfmSceneChangeForMotionEnable (HI_U32 u32Data,HI_U32 tfm_scenechangeformotion_en);
HI_VOID VDP_VID_SetTNRTfmGlobalMotionEnable         (HI_U32 u32Data,HI_U32 tfm_globalmotion_en);
HI_VOID VDP_VID_SetTNRTfmCbCrUpdataMode             (HI_U32 u32Data,HI_U32 tfm_cbcrupdate_mode);
HI_VOID VDP_VID_SetTNRTfm1DLpfMode                  (HI_U32 u32Data,HI_U32 tfm_1dlpf_mode);
HI_VOID VDP_VID_SetTNRYCMotionMode                  (HI_U32 u32Data,HI_U32 ymotion_mode, HI_U32 cmotion_mode);
HI_VOID VDP_VID_SetTNRTfmGlobalMotion               (HI_U32 u32Data,HI_U32 tfm_globalmotion);
HI_VOID VDP_VID_SetTNRTfmYMotionCK                  (HI_U32 u32Data,HI_S32 tfm_ymotion_core, HI_U32 tfm_ymotion_k);
HI_VOID VDP_VID_SetTNRTfmYEdgeCK                    (HI_U32 u32Data,HI_S32 tfm_yedge_core, HI_U32 tfm_yedge_k);
HI_VOID VDP_VID_SetTNRTmYMtMeanCK                   (HI_U32 u32Data,HI_S32 tm_ymtmean_core, HI_U32 tm_ymtmean_k);
HI_VOID VDP_VID_SetTNRTYMYCK                        (HI_U32 u32Data,HI_S32 tymy_core, HI_U32 tymy_k);
HI_VOID VDP_VID_SetTNRTYMEYCK                       (HI_U32 u32Data,HI_S32 tymey_core, HI_U32 tymey_k);
HI_VOID VDP_VID_SetTNRTCMYCK                        (HI_U32 u32Data,HI_S32 tcmy_core, HI_U32 tcmy_k);
HI_VOID VDP_VID_SetTNRTCMEYCK                       (HI_U32 u32Data,HI_S32 tcmey_core, HI_U32 tcmey_k);
HI_VOID VDP_VID_SetTNRTmCMtCK                       (HI_U32 u32Data,HI_S32 tm_cmt_core, HI_U32 tm_cmt_k);
HI_VOID VDP_VID_SetTNRTmYMtCK                       (HI_U32 u32Data,HI_S32 tm_ymt_core, HI_U32 tm_ymt_k);
HI_VOID VDP_VID_SetTNRTmCMtMeanCK                   (HI_U32 u32Data,HI_S32 tm_cmtmean_core, HI_U32 tm_cmtmean_k);
HI_VOID VDP_VID_SetTNRYCNr1dEnable                  (HI_U32 u32Data,HI_U32 ynr_1d_en, HI_U32 cnr_1d_en);
HI_VOID VDP_VID_SetTNRSenceChange                   (HI_U32 u32Data,HI_U32 sencechange);
HI_VOID VDP_VID_SetTNRCTRandNoise                   (HI_U32 u32Data,HI_U32 ctrandnoise_en, HI_U32 ctrandnoise_bit);
HI_VOID VDP_VID_SetTNRYTRandNoise                   (HI_U32 u32Data,HI_U32 ytrandnoise_en, HI_U32 ytrandnoise_bit);
HI_VOID VDP_VID_SetTNRT2DEdgeMode                   (HI_U32 u32Data,HI_U32 t2dedgemode);
HI_VOID VDP_VID_SetTNRT2DMeanEnable                 (HI_U32 u32Data,HI_U32 t2dmeanen);
HI_VOID VDP_VID_SetTNRT2DMedEnable                  (HI_U32 u32Data,HI_U32 t2dmeden);
HI_VOID VDP_VID_SetTNRT2DMMEnable                   (HI_U32 u32Data,HI_U32 t2dmmen);
HI_VOID VDP_VID_SetTNRSChange                       (HI_U32 u32Data,HI_U32 s_change);
HI_VOID VDP_VID_SetYCMotionStrengthEn               (HI_U32 u32Data,HI_U32 ymotion_strength_en, HI_S32 cmotion_strength_en);
HI_VOID VDP_VID_SetTNRT2DEdgeCK                     (HI_U32 u32Data,HI_S32 t2d_edge_core, HI_U32 t2d_edge_k);
HI_VOID VDP_VID_SetTNRT2DNoiseCK                    (HI_U32 u32Data,HI_S32 t2d_noise_core, HI_U32 t2d_noise_k);
HI_VOID VDP_VID_SetTNREdgeCMovingCK                 (HI_U32 u32Data,HI_S32 edge_cmoving_core, HI_U32 edge_cmoving_k);
HI_VOID VDP_VID_SetTNRMarketCoordinate              (HI_U32 u32Data, HI_U32 market_coordinate);
HI_VOID VDP_VID_SetTNRMotionEdgeRatioLut            (HI_U32 u32Data,HI_U32 motion_edge_ratio_lut[8][8]);
HI_VOID VDP_VID_SetTNRCbCrLut                       (HI_U32 u32Data,HI_U32 cbcr_lut[16][32]);
HI_VOID VDP_VID_SetTNRMotionEdgeLut                 (HI_U32 u32Data,HI_U32 motion_edge_lut[16][8]);
HI_VOID VDP_VID_SetTNRMotionNoiseLut                (HI_U32 u32Data,HI_U32 motion_noise_lut[16][8]);
HI_VOID VDP_VID_SetTNRYMotionStrengthLut            (HI_U32 u32Data,HI_U32 ymotion_strength_lut[32]);
HI_VOID VDP_VID_SetTNRCMotionStrengthLut            (HI_U32 u32Data,HI_U32 cmotion_strength_lut[32]);
////SNR
HI_VOID VDP_VID_SetSnrEnable                        (HI_U32 u32Data, HI_U32 u32Data1);
#if 0
HI_VOID VDP_VID_SetSnrMadRAddr                      (HI_U32 u32Data, HI_U32 u32Data1);
HI_VOID VDP_VID_SetSNRYnr2DEnable                   (HI_U32 u32Data,HI_U32 ynr2den);
HI_VOID VDP_VID_SetSNRCnr2DEnable                   (HI_U32 u32Data,HI_U32 cnr2den);
HI_VOID VDP_VID_SetSNRMotionEdgeWeightEnable        (HI_U32 u32Data,HI_U32 motionedgeweighten);
HI_VOID VDP_VID_SetSNRColorWeightEnable             (HI_U32 u32Data,HI_U32 colorweighten);
HI_VOID VDP_VID_SetSNREdgePreFilerEnable            (HI_U32 u32Data,HI_U32 edgeprefilteren);
HI_VOID VDP_VID_SetSNRMarketModeEnable              (HI_U32 u32Data,HI_U32 marketen);
HI_VOID VDP_VID_SetSNRMarketModeMux                 (HI_U32 u32Data,HI_U32 market_mux);
HI_VOID VDP_VID_SetSNRTestModeEnable                (HI_U32 u32Data,HI_U32 test_en);
HI_VOID VDP_VID_SetSNREdgeRatioRange                (HI_U32 u32Data,HI_U32 edgemaxratio, HI_U32 edgeminratio, HI_U32 edgeoriratio);
HI_VOID VDP_VID_SetSNREdgeStrRange                  (HI_U32 u32Data,HI_U32 edgemaxstrength, HI_U32 edgeminstrength, HI_U32 edgeoristrength);
HI_VOID VDP_VID_SetSNREdgeStrth                     (HI_U32 u32Data,HI_U32 edgestrth1, HI_U32 edgestrth2, HI_U32 edgestrth3);
HI_VOID VDP_VID_SetSNREdgeStrk                      (HI_U32 u32Data,HI_U32 edgestrk1, HI_U32 edgestrk2, HI_U32 edgestrk3);
HI_VOID VDP_VID_SetSNREdgeMeanth1                   (HI_U32 u32Data,HI_U32 edgemeanth1, HI_U32 edgemeanth2, HI_U32 edgemeanth3);
HI_VOID VDP_VID_SetSNREdgeMeanth2                   (HI_U32 u32Data,HI_U32 edgemeanth4, HI_U32 edgemeanth5, HI_U32 edgemeanth6);
HI_VOID VDP_VID_SetSNREdgeMeanth3                   (HI_U32 u32Data,HI_U32 edgemeanth7, HI_U32 edgemeanth8);
HI_VOID VDP_VID_SetSNREdgeMeank1                    (HI_U32 u32Data,HI_U32 edgemeank1, HI_U32 edgemeank2, HI_U32 edgemeank3, HI_U32 edgemeank4);
HI_VOID VDP_VID_SetSNREdgeMeank2                    (HI_U32 u32Data,HI_U32 edgemeank5, HI_U32 edgemeank6, HI_U32 edgemeank7, HI_U32 edgemeank8);
HI_VOID VDP_VID_SetSNRWin                           (HI_U32 u32Data,HI_U32 y2dwinwidth, HI_U32 y2dwinheight, HI_U32 c2dwinwidth, HI_U32 c2dwinheight);
HI_VOID VDP_VID_SetSNRStr                           (HI_U32 u32Data,HI_U32 ysnrstr, HI_U32 csnrstr);
HI_VOID VDP_VID_SetSNROffset                        (HI_U32 u32Data,HI_U32 stroffset0, HI_U32 stroffset1, HI_U32 stroffset2, HI_U32 stroffset3);
HI_VOID VDP_VID_SetSNRAdjust                        (HI_U32 u32Data,HI_U32 ystradjust, HI_U32 cstradjust);
HI_VOID VDP_VID_SetSNRSChangeTh                     (HI_U32 u32Data,HI_U32 scenechangeth);
HI_VOID VDP_VID_SetSNRRatio1                        (HI_U32 u32Data,HI_U32 ratio1, HI_U32 ratio2, HI_U32 ratio3);
HI_VOID VDP_VID_SetSNRRatio2                        (HI_U32 u32Data,HI_U32 ratio4, HI_U32 ratio5, HI_U32 ratio6);
HI_VOID VDP_VID_SetSNRRatio3                        (HI_U32 u32Data,HI_U32 ratio7, HI_U32 ratio8);
HI_VOID VDP_VID_SetSNREdgeStr                       (HI_U32 u32Data,HI_U32 edge1, HI_U32 edge2, HI_U32 edge3);
HI_VOID VDP_VID_SetSNRTestColor                     (HI_U32 u32Data,HI_U32 test_color_cb, HI_U32 test_color_cr);
HI_VOID VDP_VID_SetSNRSChange                       (HI_U32 u32Data,HI_U32 scenechange_info, HI_U32 scenechange_en, HI_U32 scenechange_mode1_en, HI_U32 scenechange_bldk, HI_S32 scenechange_bldcore, HI_U32 scenechange_mode2_en);
HI_VOID VDP_VID_SetSNRMotionEdgeLut                 (HI_U32 u32Data,HI_U32 motion_edge_lut[32]);
HI_VOID VDP_VID_SetSNRColorBasedLut                 (HI_U32 u32Data,HI_U32 color_based_lut[32]);
#endif
HI_VOID VDP_VID_SetSnrstrength                      (HI_U32 u32Data, HI_U32 snrstrength);
HI_VOID VDP_VID_SetSnrfiltermode                    (HI_U32 u32Data, HI_U32 snrfiltermode);
HI_VOID VDP_VID_SetMeanedgeratioen                  (HI_U32 u32Data, HI_U32 meanedgeratioen);
HI_VOID VDP_VID_SetEdgelpfmode                      (HI_U32 u32Data, HI_U32 edgelpfmode);
HI_VOID VDP_VID_SetDiredgesmoothen                  (HI_U32 u32Data, HI_U32 diredgesmoothen);
HI_VOID VDP_VID_SetDebugmode                        (HI_U32 u32Data, HI_U32 debugmode);
HI_VOID VDP_VID_SetDebugmodeen                      (HI_U32 u32Data, HI_U32 debugmodeen);
HI_VOID VDP_VID_SetDemomodelr                       (HI_U32 u32Data, HI_U32 demomodelr);
HI_VOID VDP_VID_SetDemomodeen                       (HI_U32 u32Data, HI_U32 demomodeen);
HI_VOID VDP_VID_SetBlendingmode                     (HI_U32 u32Data, HI_U32 blendingmode);
HI_VOID VDP_VID_SetEdgeonlyen                       (HI_U32 u32Data, HI_U32 edgeonlyen);
HI_VOID VDP_VID_SetMotionedgeen                     (HI_U32 u32Data, HI_U32 motionedgeen);
HI_VOID VDP_VID_SetColorweighten                    (HI_U32 u32Data, HI_U32 colorweighten);
HI_VOID VDP_VID_SetEdgeprelpfen                     (HI_U32 u32Data, HI_U32 edgeprelpfen);
HI_VOID VDP_VID_SetChromasnren                      (HI_U32 u32Data, HI_U32 chromasnren);
HI_VOID VDP_VID_SetLumasnren                        (HI_U32 u32Data, HI_U32 lumasnren);
HI_VOID VDP_VID_SetMeanedgeratiox2                  (HI_U32 u32Data, HI_U32 meanedgeratiox2);
HI_VOID VDP_VID_SetMeanedgeratiox1                  (HI_U32 u32Data, HI_U32 meanedgeratiox1);
HI_VOID VDP_VID_SetMeanedgeratiox0                  (HI_U32 u32Data, HI_U32 meanedgeratiox0);
HI_VOID VDP_VID_SetMeanedgeratiox5                  (HI_U32 u32Data, HI_U32 meanedgeratiox5);
HI_VOID VDP_VID_SetMeanedgeratiox4                  (HI_U32 u32Data, HI_U32 meanedgeratiox4);
HI_VOID VDP_VID_SetMeanedgeratiox3                  (HI_U32 u32Data, HI_U32 meanedgeratiox3);
HI_VOID VDP_VID_SetMeanedgeratioy2                  (HI_U32 u32Data, HI_U32 meanedgeratioy2);
HI_VOID VDP_VID_SetMeanedgeratioy1                  (HI_U32 u32Data, HI_U32 meanedgeratioy1);
HI_VOID VDP_VID_SetMeanedgeratioy0                  (HI_U32 u32Data, HI_U32 meanedgeratioy0);
HI_VOID VDP_VID_SetMeanedgeratioy4                  (HI_U32 u32Data, HI_U32 meanedgeratioy4);
HI_VOID VDP_VID_SetMeanedgeratioy3                  (HI_U32 u32Data, HI_U32 meanedgeratioy3);
HI_VOID VDP_VID_SetMeanedgeratiok1                  (HI_U32 u32Data, HI_U32 meanedgeratiok1);
HI_VOID VDP_VID_SetMeanedgeratiok0                  (HI_U32 u32Data, HI_U32 meanedgeratiok0);
HI_VOID VDP_VID_SetMeanedgeratiok3                  (HI_U32 u32Data, HI_U32 meanedgeratiok3);
HI_VOID VDP_VID_SetMeanedgeratiok2                  (HI_U32 u32Data, HI_U32 meanedgeratiok2);
HI_VOID VDP_VID_SetMeanedgeratiomin                 (HI_U32 u32Data, HI_U32 meanedgeratiomin);
HI_VOID VDP_VID_SetMeanedgeratiomax                 (HI_U32 u32Data, HI_U32 meanedgeratiomax);
HI_VOID VDP_VID_SetEdgestrmappingx2                 (HI_U32 u32Data, HI_U32 edgestrmappingx2);
HI_VOID VDP_VID_SetEdgestrmappingx1                 (HI_U32 u32Data, HI_U32 edgestrmappingx1);
HI_VOID VDP_VID_SetEdgestrmappingx0                 (HI_U32 u32Data, HI_U32 edgestrmappingx0);
HI_VOID VDP_VID_SetEdgestrmappingx5                 (HI_U32 u32Data, HI_U32 edgestrmappingx5);
HI_VOID VDP_VID_SetEdgestrmappingx4                 (HI_U32 u32Data, HI_U32 edgestrmappingx4);
HI_VOID VDP_VID_SetEdgestrmappingx3                 (HI_U32 u32Data, HI_U32 edgestrmappingx3);
HI_VOID VDP_VID_SetEdgestrmappingx7                 (HI_U32 u32Data, HI_U32 edgestrmappingx7);
HI_VOID VDP_VID_SetEdgestrmappingx6                 (HI_U32 u32Data, HI_U32 edgestrmappingx6);
HI_VOID VDP_VID_SetEdgestrmappingy3                 (HI_U32 u32Data, HI_U32 edgestrmappingy3);
HI_VOID VDP_VID_SetEdgestrmappingy2                 (HI_U32 u32Data, HI_U32 edgestrmappingy2);
HI_VOID VDP_VID_SetEdgestrmappingy1                 (HI_U32 u32Data, HI_U32 edgestrmappingy1);
HI_VOID VDP_VID_SetEdgestrmappingy0                 (HI_U32 u32Data, HI_U32 edgestrmappingy0);
HI_VOID VDP_VID_SetEdgestrmappingy6                 (HI_U32 u32Data, HI_U32 edgestrmappingy6);
HI_VOID VDP_VID_SetEdgestrmappingy5                 (HI_U32 u32Data, HI_U32 edgestrmappingy5);
HI_VOID VDP_VID_SetEdgestrmappingy4                 (HI_U32 u32Data, HI_U32 edgestrmappingy4);
HI_VOID VDP_VID_SetEdgestrmappingk2                 (HI_U32 u32Data, HI_U32 edgestrmappingk2);
HI_VOID VDP_VID_SetEdgestrmappingk1                 (HI_U32 u32Data, HI_U32 edgestrmappingk1);
HI_VOID VDP_VID_SetEdgestrmappingk0                 (HI_U32 u32Data, HI_U32 edgestrmappingk0);
HI_VOID VDP_VID_SetEdgestrmappingk5                 (HI_U32 u32Data, HI_U32 edgestrmappingk5);
HI_VOID VDP_VID_SetEdgestrmappingk4                 (HI_U32 u32Data, HI_U32 edgestrmappingk4);
HI_VOID VDP_VID_SetEdgestrmappingk3                 (HI_U32 u32Data, HI_U32 edgestrmappingk3);
HI_VOID VDP_VID_SetEdgestrmappingmax                (HI_U32 u32Data, HI_U32 edgestrmappingmax);
HI_VOID VDP_VID_SetEdgestrmappingmin                (HI_U32 u32Data, HI_U32 edgestrmappingmin);
HI_VOID VDP_VID_SetSfymaxedgevalthd3                (HI_U32 u32Data, HI_U32 sfymaxedgevalthd3);
HI_VOID VDP_VID_SetSfymaxedgevalthd2                (HI_U32 u32Data, HI_U32 sfymaxedgevalthd2);
HI_VOID VDP_VID_SetSfymaxedgevalthd1                (HI_U32 u32Data, HI_U32 sfymaxedgevalthd1);
HI_VOID VDP_VID_SetSfymaxedgeidxthd3                (HI_U32 u32Data, HI_U32 sfymaxedgeidxthd3);
HI_VOID VDP_VID_SetSfymaxedgeidxthd2                (HI_U32 u32Data, HI_U32 sfymaxedgeidxthd2);
HI_VOID VDP_VID_SetSfymaxedgeidxthd1                (HI_U32 u32Data, HI_U32 sfymaxedgeidxthd1);
HI_VOID VDP_VID_SetSfymeanedgevalthd3               (HI_U32 u32Data, HI_U32 sfymeanedgevalthd3);
HI_VOID VDP_VID_SetSfymeanedgevalthd2               (HI_U32 u32Data, HI_U32 sfymeanedgevalthd2);
HI_VOID VDP_VID_SetSfymeanedgevalthd1               (HI_U32 u32Data, HI_U32 sfymeanedgevalthd1);
HI_VOID VDP_VID_SetWfymaxedgevalthd3                (HI_U32 u32Data, HI_U32 wfymaxedgevalthd3);
HI_VOID VDP_VID_SetWfymaxedgevalthd2                (HI_U32 u32Data, HI_U32 wfymaxedgevalthd2);
HI_VOID VDP_VID_SetWfymaxedgevalthd1                (HI_U32 u32Data, HI_U32 wfymaxedgevalthd1);
HI_VOID VDP_VID_SetWfymaxedgeidxthd3                (HI_U32 u32Data, HI_U32 wfymaxedgeidxthd3);
HI_VOID VDP_VID_SetWfymaxedgeidxthd2                (HI_U32 u32Data, HI_U32 wfymaxedgeidxthd2);
HI_VOID VDP_VID_SetWfymaxedgeidxthd1                (HI_U32 u32Data, HI_U32 wfymaxedgeidxthd1);
HI_VOID VDP_VID_SetWfymeanedgevalthd3               (HI_U32 u32Data, HI_U32 wfymeanedgevalthd3);
HI_VOID VDP_VID_SetWfymeanedgevalthd2               (HI_U32 u32Data, HI_U32 wfymeanedgevalthd2);
HI_VOID VDP_VID_SetWfymeanedgevalthd1               (HI_U32 u32Data, HI_U32 wfymeanedgevalthd1);
HI_VOID VDP_VID_SetSfcmaxedgevalthd2                (HI_U32 u32Data, HI_U32 sfcmaxedgevalthd2);
HI_VOID VDP_VID_SetSfcmaxedgevalthd1                (HI_U32 u32Data, HI_U32 sfcmaxedgevalthd1);
HI_VOID VDP_VID_SetSfcmaxedgeidxthd2                (HI_U32 u32Data, HI_U32 sfcmaxedgeidxthd2);
HI_VOID VDP_VID_SetSfcmaxedgeidxthd1                (HI_U32 u32Data, HI_U32 sfcmaxedgeidxthd1);
HI_VOID VDP_VID_SetSfcmeanedgevalthd2               (HI_U32 u32Data, HI_U32 sfcmeanedgevalthd2);
HI_VOID VDP_VID_SetSfcmeanedgevalthd1               (HI_U32 u32Data, HI_U32 sfcmeanedgevalthd1);
HI_VOID VDP_VID_SetWfcmaxedgevalthd2                (HI_U32 u32Data, HI_U32 wfcmaxedgevalthd2);
HI_VOID VDP_VID_SetWfcmaxedgevalthd1                (HI_U32 u32Data, HI_U32 wfcmaxedgevalthd1);
HI_VOID VDP_VID_SetWfcmaxedgeidxthd2                (HI_U32 u32Data, HI_U32 wfcmaxedgeidxthd2);
HI_VOID VDP_VID_SetWfcmaxedgeidxthd1                (HI_U32 u32Data, HI_U32 wfcmaxedgeidxthd1);
HI_VOID VDP_VID_SetWfcmeanedgevalthd2               (HI_U32 u32Data, HI_U32 wfcmeanedgevalthd2);
HI_VOID VDP_VID_SetWfcmeanedgevalthd1               (HI_U32 u32Data, HI_U32 wfcmeanedgevalthd1);
HI_VOID VDP_VID_SetCdefaultfiltertype               (HI_U32 u32Data, HI_U32 cdefaultfiltertype);
HI_VOID VDP_VID_SetYdefaultfiltertype               (HI_U32 u32Data, HI_U32 ydefaultfiltertype);
HI_VOID VDP_VID_SetNonoisegain                      (HI_U32 u32Data, HI_U32 nonoisegain);
HI_VOID VDP_VID_SetNoisecore                        (HI_U32 u32Data, HI_U32 noisecore);
HI_VOID VDP_VID_SetRandyinnoiselevel                (HI_U32 u32Data, HI_U32 randyinnoiselevel);
HI_VOID VDP_VID_SetAddrandyinnoiseen                (HI_U32 u32Data, HI_U32 addrandyinnoiseen);
HI_VOID VDP_VID_SetDiffabssumofst                   (HI_U32 u32Data, HI_U32 diffabssumofst);
HI_VOID VDP_VID_SetSclabssum                        (HI_U32 u32Data, HI_U32 sclabssum);
HI_VOID VDP_VID_SetEdgeindicatorsel                 (HI_U32 u32Data, HI_U32 edgeindicatorsel);
HI_VOID VDP_VID_SetWinactdirdiffthr                 (HI_U32 u32Data, HI_U32 winactdirdiffthr);
HI_VOID VDP_VID_SetWinactthr                        (HI_U32 u32Data, HI_U32 winactthr);
HI_VOID VDP_VID_SetPixdirstrthr1                    (HI_U32 u32Data, HI_U32 pixdirstrthr1);
HI_VOID VDP_VID_SetPixdirstrthr0                    (HI_U32 u32Data, HI_U32 pixdirstrthr0);
HI_VOID VDP_VID_SetPixdirstrthr3                    (HI_U32 u32Data, HI_U32 pixdirstrthr3);
HI_VOID VDP_VID_SetPixdirstrthr2                    (HI_U32 u32Data, HI_U32 pixdirstrthr2);
HI_VOID VDP_VID_SetPixdirstrthr5                    (HI_U32 u32Data, HI_U32 pixdirstrthr5);
HI_VOID VDP_VID_SetPixdirstrthr4                    (HI_U32 u32Data, HI_U32 pixdirstrthr4);
HI_VOID VDP_VID_SetPixdirstrthr7                    (HI_U32 u32Data, HI_U32 pixdirstrthr7);
HI_VOID VDP_VID_SetPixdirstrthr6                    (HI_U32 u32Data, HI_U32 pixdirstrthr6);
HI_VOID VDP_VID_SetMediff3thrdir0                   (HI_U32 u32Data, HI_U32 mediff3thrdir0);
HI_VOID VDP_VID_SetMediffcntmintenthrdir0           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir0);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir0            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir0);
HI_VOID VDP_VID_SetMediffcntminnorthrdir0           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir0);
HI_VOID VDP_VID_SetMediff3thrdir1                   (HI_U32 u32Data, HI_U32 mediff3thrdir1);
HI_VOID VDP_VID_SetMediffcntmintenthrdir1           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir1);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir1            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir1);
HI_VOID VDP_VID_SetMediffcntminnorthrdir1           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir1);
HI_VOID VDP_VID_SetMediff3thrdir2                   (HI_U32 u32Data, HI_U32 mediff3thrdir2);
HI_VOID VDP_VID_SetMediffcntmintenthrdir2           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir2);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir2            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir2);
HI_VOID VDP_VID_SetMediffcntminnorthrdir2           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir2);
HI_VOID VDP_VID_SetMediff3thrdir3                   (HI_U32 u32Data, HI_U32 mediff3thrdir3);
HI_VOID VDP_VID_SetMediffcntmintenthrdir3           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir3);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir3            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir3);
HI_VOID VDP_VID_SetMediffcntminnorthrdir3           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir3);
HI_VOID VDP_VID_SetMediff3thrdir4                   (HI_U32 u32Data, HI_U32 mediff3thrdir4);
HI_VOID VDP_VID_SetMediffcntmintenthrdir4           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir4);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir4            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir4);
HI_VOID VDP_VID_SetMediffcntminnorthrdir4           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir4);
HI_VOID VDP_VID_SetMediff3thrdir5                   (HI_U32 u32Data, HI_U32 mediff3thrdir5);
HI_VOID VDP_VID_SetMediffcntmintenthrdir5           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir5);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir5            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir5);
HI_VOID VDP_VID_SetMediffcntminnorthrdir5           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir5);
HI_VOID VDP_VID_SetMediff3thrdir6                   (HI_U32 u32Data, HI_U32 mediff3thrdir6);
HI_VOID VDP_VID_SetMediffcntmintenthrdir6           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir6);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir6            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir6);
HI_VOID VDP_VID_SetMediffcntminnorthrdir6           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir6);
HI_VOID VDP_VID_SetMediff3thrdir7                   (HI_U32 u32Data, HI_U32 mediff3thrdir7);
HI_VOID VDP_VID_SetMediffcntmintenthrdir7           (HI_U32 u32Data, HI_U32 mediffcntmintenthrdir7);
HI_VOID VDP_VID_SetWinmeanhordiffthrdir7            (HI_U32 u32Data, HI_U32 winmeanhordiffthrdir7);
HI_VOID VDP_VID_SetMediffcntminnorthrdir7           (HI_U32 u32Data, HI_U32 mediffcntminnorthrdir7);
HI_VOID VDP_VID_SetDemomodecoor                     (HI_U32 u32Data, HI_U32 demomodecoor);
HI_VOID VDP_VID_SetSnrMotionEdgeLut                 (HI_U32 u32Data, HI_U32 snrmotionedgelut[16][32]);
HI_VOID VPSS_DRV_SetSnrColorBasedLut                (HI_U32 u32Data, HI_U32 snrcbcrlut[16][16]);

//DBM
HI_VOID VDP_VID_SetDbmEnable                        (HI_U32 u32Data, HI_U32 u32Data1);
HI_VOID VDP_VID_SetDbmDetEnable                     (HI_U32 u32Data, HI_U32 u32Data1);
HI_VOID VDP_VID_SetDbmProtocol                      (HI_U32 u32Data, HI_U32 dbm_protocol);
HI_VOID VDP_VID_SetDbmOutSelGain                    (HI_U32 u32Data, HI_U32 dbm_out_sel_gain);
HI_VOID VDP_VID_SetDbmOutMode                       (HI_U32 u32Data, HI_U32 dbm_out_mode);
HI_VOID VDP_VID_SetDetVyEn                          (HI_U32 u32Data, HI_U32 det_vy_en);
HI_VOID VDP_VID_SetDetHcEn                          (HI_U32 u32Data, HI_U32 det_hc_en);
HI_VOID VDP_VID_SetDetHyEn                          (HI_U32 u32Data, HI_U32 det_hy_en);
HI_VOID VDP_VID_SetDbmDemoMode                      (HI_U32 u32Data, HI_U32 dbm_demo_mode);
HI_VOID VDP_VID_SetDbmDemoEn                        (HI_U32 u32Data, HI_U32 dbm_demo_en);
//HI_VOID VDP_VID_SetDbChrHorMidGreyEn              (HI_U32 u32Data, HI_U32 db_chr_hor_mid_grey_en);
//HI_VOID VDP_VID_SetDbChrHorEn                     (HI_U32 u32Data, HI_U32 db_chr_hor_en);
//HI_VOID VDP_VID_SetDbChrVerEn                     (HI_U32 u32Data, HI_U32 db_chr_ver_en);
HI_VOID VDP_VID_SetDbLumHorEn                       (HI_U32 u32Data, HI_U32 db_lum_hor_en);
HI_VOID VDP_VID_SetDbLumVerEn                       (HI_U32 u32Data, HI_U32 db_lum_ver_en);
HI_VOID VDP_VID_SetDrEn                             (HI_U32 u32Data, HI_U32 dr_en);
HI_VOID VDP_VID_SetDsEn                             (HI_U32 u32Data, HI_U32 ds_en);
HI_VOID VDP_VID_SetDmEn                             (HI_U32 u32Data, HI_U32 dm_en);
HI_VOID VDP_VID_SetDbEn                             (HI_U32 u32Data, HI_U32 db_en);
//HI_VOID VDP_VID_SetDbLumHBorderStrLut             (HI_U32 u32Data, HI_U32 db_lum_h_border_str_lut_p[136]);
//HI_VOID VDP_VID_SetDbLumVBorderStrLut             (HI_U32 u32Data, HI_U32 db_lum_v_border_str_lut_p[136]);
HI_VOID VDP_VID_SetDbLumHStrFadeLut1                (HI_U32 u32Data, HI_U32 db_lum_h_str_fade_lut1_p[2]);
HI_VOID VDP_VID_SetDbLumHStrFadeLut2                (HI_U32 u32Data, HI_U32 db_lum_h_str_fade_lut2_p[4]);
HI_VOID VDP_VID_SetDbLumHStrFadeLut3                (HI_U32 u32Data, HI_U32 db_lum_h_str_fade_lut3_p[8]);
HI_VOID VDP_VID_SetDbLumHStrFageLut4                (HI_U32 u32Data, HI_U32 db_lum_h_str_fade_lut4_p[12]);
HI_VOID VDP_VID_SetDbLumVStrFadeLut                 (HI_U32 u32Data, HI_U32 db_lum_v_str_fade_lut_p[4]);
//HI_VOID VDP_VID_SetDbQpStrLut                     (HI_U32 u32Data, HI_U32 db_qp_str_lut_p[16]);
HI_VOID VDP_VID_SetDbSobelStrLut                    (HI_U32 u32Data, HI_U32 db_sobel_str_lut_p[26]);
HI_VOID VDP_VID_SetDbDirStrLut                      (HI_U32 u32Data, HI_U32 db_dir_str_lut_p[16]);
HI_VOID VDP_VID_SetDbDirStrGainLut                  (HI_U32 u32Data, HI_U32 db_dir_str_gain_lut_p[10]);
HI_VOID VDP_VID_SetDbDiffMapLut                     (HI_U32 u32Data, HI_U32 db_diff_map_lut_p[8]);
HI_VOID VDP_VID_SetDbDiffWeightLut                  (HI_U32 u32Data, HI_U32 db_diff_weight_lut_p[8]);
HI_VOID VDP_VID_SetDbDiffStrLut                     (HI_U32 u32Data, HI_U32 db_diff_str_lut_p[8]);
HI_VOID VDP_VID_SetDbStrethEn                       (HI_U32 u32Data, HI_U32 db_streth_en);
HI_VOID VDP_VID_SetDbBlkPosMode                     (HI_U32 u32Data, HI_U32 db_blk_pos_mode);
HI_VOID VDP_VID_SetDbBlkMode                        (HI_U32 u32Data, HI_U32 db_blk_mode);
//HI_VOID VDP_VID_SetDbFltStrCalcMode               (HI_U32 u32Data, HI_U32 db_flt_str_calc_mode);
//HI_VOID VDP_VID_SetDbImageStruct                  (HI_U32 u32Data, HI_U32 db_image_struct);
//HI_VOID VDP_VID_SetDbMp2QScaleType                (HI_U32 u32Data, HI_U32 db_mp2_q_scale_type);
//HI_VOID VDP_VID_SetDbTopOrBot                     (HI_U32 u32Data, HI_U32 db_top_or_bot);
HI_VOID VDP_VID_SetDbVdhTransInfoEn                 (HI_U32 u32Data, HI_U32 db_vdh_trans_info_en);
HI_VOID VDP_VID_SetDbDetEn                          (HI_U32 u32Data, HI_U32 db_det_en);
//HI_VOID VDP_VID_SetDbSingleEn                     (HI_U32 u32Data, HI_U32 db_single_en);
//HI_VOID VDP_VID_SetDbDeiEn                        (HI_U32 u32Data, HI_U32 db_dei_en);
//HI_VOID VDP_VID_SetDbLumVbsCalcMode               (HI_U32 u32Data, HI_U32 db_lum_vbs_calc_mode);
//HI_VOID VDP_VID_SetDbLumHbsCalcMode               (HI_U32 u32Data, HI_U32 db_lum_hbs_calc_mode);
//HI_VOID VDP_VID_SetDbQpEn                         (HI_U32 u32Data, HI_U32 db_qp_en);
//HI_VOID VDP_VID_SetDbAvgQp                        (HI_U32 u32Data, HI_U32 db_avg_qp);
HI_VOID VDP_VID_SetDbCtrstThresh                    (HI_U32 u32Data, HI_U32 db_ctrst_thresh);
HI_VOID VDP_VID_SetDbGradSubRatio                   (HI_U32 u32Data, HI_U32 db_grad_sub_ratio);
HI_VOID VDP_VID_SetDbDirSmoothMode                  (HI_U32 u32Data, HI_U32 db_dir_smooth_mode);
HI_VOID VDP_VID_SetDbLumVBorderStrTh                (HI_U32 u32Data, HI_U32 db_lum_v_border_str_th);
HI_VOID VDP_VID_SetDbLumHBorderStrTh                (HI_U32 u32Data, HI_U32 db_lum_h_border_str_th);
HI_VOID VDP_VID_SetDbDetectRatioV                   (HI_U32 u32Data, HI_U32 db_detect_ratio_v);
HI_VOID VDP_VID_SetDbDetectRatioH                   (HI_U32 u32Data, HI_U32 db_detect_ratio_h);
HI_VOID VDP_VID_SetDbTextStrGain                    (HI_U32 u32Data, HI_U32 db_text_str_gain);
//HI_VOID VDP_VID_SetDbTextAdpGain                  (HI_U32 u32Data, HI_U32 db_text_adp_gain);
//HI_VOID VDP_VID_SetDbSkipGain                     (HI_U32 u32Data, HI_U32 db_skip_gain);
//HI_VOID VDP_VID_SetDbMaxLumHorDbDist              (HI_U32 u32Data, HI_U32 db_max_lum_hor_db_dist);
HI_VOID VDP_VID_SetDbSttOffsetY                     (HI_U32 u32Data, HI_U32 db_stt_offset_y);
HI_VOID VDP_VID_SetDbSttOffsetX                     (HI_U32 u32Data, HI_U32 db_stt_offset_x);
HI_VOID VDP_VID_SetDbEndOffsetY                     (HI_U32 u32Data, HI_U32 db_end_offset_y);
HI_VOID VDP_VID_SetDbEndOffsetX                     (HI_U32 u32Data, HI_U32 db_end_offset_x);
HI_VOID VDP_VID_SetDbDemoPosX                       (HI_U32 u32Data, HI_U32 db_demo_pos_x);
HI_VOID VDP_VID_SetDbLumHorDeltaLut                 (HI_U32 u32Data,HI_U32 db_lum_hor_delta_lut_p[16]);
HI_VOID VDP_VID_SetDbLumVerDeltaLut                 (HI_U32 u32Data,HI_U32 db_lum_ver_delta_lut_p[16]);
//HI_VOID VDP_VID_SetDbTextAdpGain2                 (HI_U32 u32Data, HI_U32 db_text_adp_gain2);
//HI_VOID VDP_VID_SetDbTextAdpGain1                 (HI_U32 u32Data, HI_U32 db_text_adp_gain1);
//HI_VOID VDP_VID_SetDbFltAdpGain2                  (HI_U32 u32Data, HI_U32 db_flt_adp_gain2);
//HI_VOID VDP_VID_SetDbFltAdpGain1                  (HI_U32 u32Data, HI_U32 db_flt_adp_gain1);
//HI_VOID VDP_VID_SetDbFltAdpGain                   (HI_U32 u32Data, HI_U32 db_flt_adp_gain);
HI_VOID VDP_VID_SetDbGlobalDbStrengthLum            (HI_U32 u32Data, HI_U32 db_global_db_strength_lum);
HI_VOID VDP_VID_SetDbBlkHeight                      (HI_U32 u32Data, HI_U32 db_blk_height);
HI_VOID VDP_VID_SetDbBlkWidth                       (HI_U32 u32Data, HI_U32 db_blk_width);
HI_VOID VDP_VID_SetDbLumHorGain2                    (HI_U32 u32Data, HI_U32 db_lum_hor_gain2);
HI_VOID VDP_VID_SetDbLumHorGain1                    (HI_U32 u32Data, HI_U32 db_lum_hor_gain1);
HI_VOID VDP_VID_SetDbLumHorVarCore                  (HI_U32 u32Data, HI_U32 db_lum_hor_var_core);

HI_VOID VDP_VID_SetDBDThdEdge                       (HI_U32 u32Data,HI_U32 hy_thd_edge,HI_U32 hc_thd_edge, HI_U32 vy_thd_edge);
HI_VOID VDP_VID_SetDBDThdTxt                        (HI_U32 u32Data,HI_U32 hy_thd_txt,HI_U32 hc_thd_txt, HI_U32 vy_thd_txt);
HI_VOID VDP_VID_SetDBDDetWgtLut                     (HI_U32 u32Data,HI_U32 det_lut_wgt[16]);
HI_VOID VDP_VID_SetDBDRtnBdTxt                      (HI_U32 u32Data,HI_U32 hy_rtn_bd_txt,HI_U32 hc_rtn_bd_txt, HI_U32 vy_rtn_bd_txt);
HI_VOID VDP_VID_SetDBDTstBlkNum                     (HI_U32 u32Data,HI_U32 hy_tst_blk_num,HI_U32 hc_tst_blk_num, HI_U32 vy_tst_blk_num);
HI_VOID VDP_VID_SetDBDHorLumaRdx8BinLut             (HI_U32 u32Data,HI_U32 hy_rdx8bin_lut[7]);
HI_VOID VDP_VID_SetDBDHorChromRdx8BinLut            (HI_U32 u32Data,HI_U32 hc_rdx8bin_lut[7]);
HI_VOID VDP_VID_SetDBDVerLumaRdx8BinLut             (HI_U32 u32Data,HI_U32 vy_rdx8bin_lut[7]);
HI_VOID VDP_VID_SetDBDMinBlkSize                    (HI_U32 u32Data,HI_U32 min_blk_size);
HI_VOID VDP_VID_SetDBDMaxBlkSize                    (HI_U32 u32Data,HI_U32 hy_max_blk_size,HI_U32 hc_max_blk_size,HI_U32 vy_max_blk_size);

HI_VOID VDP_VID_SetDmOppAngCtrstDiv                 (HI_U32 u32Data, HI_U32 dm_opp_ang_ctrst_div);
HI_VOID VDP_VID_SetDmOppAngCtrstT                   (HI_U32 u32Data, HI_U32 dm_opp_ang_ctrst_t);
HI_VOID VDP_VID_SetDmCtrstThresh                    (HI_U32 u32Data, HI_U32 dm_ctrst_thresh);
HI_VOID VDP_VID_SetDmGradSubRatio                   (HI_U32 u32Data, HI_U32 dm_grad_sub_ratio);
HI_VOID VDP_VID_SetDmStrIdxFlag                     (HI_U32 u32Data, HI_U32 dm_str_idx_flag);
HI_VOID VDP_VID_SetDmGlobalStr                      (HI_U32 u32Data, HI_U32 dm_global_str);
HI_VOID VDP_VID_SetDmSwThrGain                      (HI_U32 u32Data, HI_U32 dm_sw_thr_gain);
HI_VOID VDP_VID_SetDmEdgeGain                       (HI_U32 u32Data,HI_U32 dm_edge_gain1,HI_U32 dm_edge_gain2 );
HI_VOID VDP_VID_SetDmAsymtrcGain                    (HI_U32 u32Data, HI_U32 dm_asymtrc_gain);
HI_VOID VDP_VID_SetDmEdgeThr                        (HI_U32 u32Data, HI_U32 dm_edge_thr);
HI_VOID VDP_VID_SetDmSwWhtLut                       (HI_U32 u32Data,HI_U32 dm_sw_wht_lut[5]);
HI_VOID VDP_VID_SetDmLimitT10                       (HI_U32 u32Data, HI_U32 dm_limit_t_10);
HI_VOID VDP_VID_SetDmLimitT                         (HI_U32 u32Data, HI_U32 dm_limit_t);
HI_VOID VDP_VID_SetDmDirStrGainLut                  (HI_U32 u32Data,HI_U32 dm_dir_str_gain_lut[8]);
HI_VOID VDP_VID_SetDmDirStrLut                      (HI_U32 u32Data,HI_U32 dm_dir_str_lut[16]);
HI_VOID VDP_VID_SetDmMmfLimitEn                     (HI_U32 u32Data, HI_U32 dm_mmf_limit_en);
HI_VOID VDP_VID_SetDmDirMmfEn                       (HI_U32 u32Data, HI_U32 dm_dir_mmf_en);
HI_VOID VDP_VID_SetDmSimDirPtCountT                 (HI_U32 u32Data, HI_U32 dm_sim_dir_pt_count_t);
HI_VOID VDP_VID_SetDmMndirOppCtrstT                 (HI_U32 u32Data, HI_U32 dm_mndir_opp_ctrst_t);
HI_VOID VDP_VID_SetDmDirCtrstT10                    (HI_U32 u32Data, HI_U32 dm_dir_ctrst_t_10);
HI_VOID VDP_VID_SetDmDirCtrstT                      (HI_U32 u32Data, HI_U32 dm_dir_ctrst_t);
HI_VOID VDP_VID_SetDmCswTrsntSt10                   (HI_U32 u32Data, HI_U32 dm_csw_trsnt_st_10);
HI_VOID VDP_VID_SetDmDirStrenShiftFac               (HI_U32 u32Data, HI_U32 dm_dir_stren_shift_fac);
HI_VOID VDP_VID_SetDmDirOppCtrstT10                 (HI_U32 u32Data, HI_U32 dm_dir_opp_ctrst_t_10);
HI_VOID VDP_VID_SetDmDirOppCtrstT                   (HI_U32 u32Data, HI_U32 dm_dir_opp_ctrst_t);
HI_VOID VDP_VID_SetDmLswRatio                       (HI_U32 u32Data, HI_U32 dm_lsw_ratio);
HI_VOID VDP_VID_SetDmSdbwMode                       (HI_U32 u32Data, HI_U32 dm_sdbw_mode);
HI_VOID VDP_VID_SetDmCswTrsntSt                     (HI_U32 u32Data, HI_U32 dm_csw_trsnt_st);
HI_VOID VDP_VID_SetDmLwCtrstT10                     (HI_U32 u32Data, HI_U32 dm_lw_ctrst_t_10);
HI_VOID VDP_VID_SetDmLwCtrstT                       (HI_U32 u32Data, HI_U32 dm_lw_ctrst_t);
HI_VOID VDP_VID_SetDmCswTrsntLt                     (HI_U32 u32Data, HI_U32 dm_csw_trsnt_lt);
HI_VOID VDP_VID_SetDmMmfLr10                        (HI_U32 u32Data, HI_U32 dm_mmf_lr_10);
HI_VOID VDP_VID_SetDmMmfLr                          (HI_U32 u32Data, HI_U32 dm_mmf_lr);
HI_VOID VDP_VID_SetDmCswTrsntLt10                   (HI_U32 u32Data, HI_U32 dm_csw_trsnt_lt_10);
HI_VOID VDP_VID_SetDmMmfSr10                        (HI_U32 u32Data, HI_U32 dm_mmf_sr_10);
HI_VOID VDP_VID_SetDmMmfSr                          (HI_U32 u32Data, HI_U32 dm_mmf_sr);
HI_VOID VDP_VID_SetDmDirMmfLr10                     (HI_U32 u32Data, HI_U32 dm_dir_mmf_lr_10);
HI_VOID VDP_VID_SetDmDirMmfLr                       (HI_U32 u32Data, HI_U32 dm_dir_mmf_lr);
HI_VOID VDP_VID_SetDmDirMmfSr10                     (HI_U32 u32Data, HI_U32 dm_dir_mmf_sr_10);
HI_VOID VDP_VID_SetDmDirMmfSr                       (HI_U32 u32Data, HI_U32 dm_dir_mmf_sr);
HI_VOID VDP_VID_SetDmDirBlendStr                    (HI_U32 u32Data, HI_U32 dm_dir_blend_str);
HI_VOID VDP_VID_SetDmLimResBlendStr2                (HI_U32 u32Data, HI_U32 dm_lim_res_blend_str2);
HI_VOID VDP_VID_SetDmLimResBlendStr1                (HI_U32 u32Data, HI_U32 dm_lim_res_blend_str1);
HI_VOID VDP_VID_SetDmLimitLswRatio                  (HI_U32 u32Data, HI_U32 dm_limit_lsw_ratio);
HI_VOID VDP_VID_SetDmLimTransWid                    (HI_U32 u32Data, HI_U32 dm_lim_trans_wid);
HI_VOID VDP_VID_SetDmMinLimValTrans                 (HI_U32 u32Data, HI_U32 dm_min_lim_val_trans);
HI_VOID VDP_VID_SetDmMinLimTransWid                 (HI_U32 u32Data, HI_U32 dm_min_lim_trans_wid);
HI_VOID VDP_VID_SetDmLimTransWid10                  (HI_U32 u32Data, HI_U32 dm_lim_trans_wid_10);
HI_VOID VDP_VID_SetDmMinLimValTrans10               (HI_U32 u32Data, HI_U32 dm_min_lim_val_trans_10);
HI_VOID VDP_VID_SetDmMinLimTransWid10               (HI_U32 u32Data, HI_U32 dm_min_lim_trans_wid_10);

HI_VOID VDP_VID_SetDsFlatthrscl                     (HI_U32 u32Data, HI_U32 ds_flatthrscl);
HI_VOID VDP_VID_SetDsCordirthr                      (HI_U32 u32Data, HI_U32 ds_cordirthr);
HI_VOID VDP_VID_SetDsBlendgain                      (HI_U32 u32Data, HI_U32 ds_blendgain);
HI_VOID VDP_VID_SetDsPatcond3thr3                   (HI_U32 u32Data, HI_U32 ds_patcond3thr3);
HI_VOID VDP_VID_SetDsPatcond5thr5                   (HI_U32 u32Data, HI_U32 ds_patcond5thr5);
HI_VOID VDP_VID_SetDsPatcond6scl61                  (HI_U32 u32Data, HI_U32 ds_patcond6scl61);
HI_VOID VDP_VID_SetDsPatcond6scl62                  (HI_U32 u32Data, HI_U32 ds_patcond6scl62);
HI_VOID VDP_VID_SetDsPatcond6scl63                  (HI_U32 u32Data, HI_U32 ds_patcond6scl63);
HI_VOID VDP_VID_SetDsPatcond6scl64                  (HI_U32 u32Data, HI_U32 ds_patcond6scl64);
HI_VOID VDP_VID_SetDsPatcond6scl65                  (HI_U32 u32Data, HI_U32 ds_patcond6scl65);
HI_VOID VDP_VID_SetDsPatcond6scl66                  (HI_U32 u32Data, HI_U32 ds_patcond6scl66);
HI_VOID VDP_VID_SetDsWincond1thr1                   (HI_U32 u32Data, HI_U32 ds_wincond1thr1);
HI_VOID VDP_VID_SetDsWincond1val1                   (HI_U32 u32Data, HI_U32 ds_wincond1val1);
HI_VOID VDP_VID_SetDsWincond2thr1                   (HI_U32 u32Data, HI_U32 ds_wincond2thr1);
HI_VOID VDP_VID_SetDsWincond2val1                   (HI_U32 u32Data, HI_U32 ds_wincond2val1);
HI_VOID VDP_VID_SetDsWincond2thr2                   (HI_U32 u32Data, HI_U32 ds_wincond2thr2);
HI_VOID VDP_VID_SetDsWincond2val2                   (HI_U32 u32Data, HI_U32 ds_wincond2val2);
HI_VOID VDP_VID_SetDsWincond3thr1                   (HI_U32 u32Data, HI_U32 ds_wincond3thr1);
HI_VOID VDP_VID_SetDsWincond3val1                   (HI_U32 u32Data, HI_U32 ds_wincond3val1);
HI_VOID VDP_VID_SetDsWincond3val2                   (HI_U32 u32Data, HI_U32 ds_wincond3val2);
HI_VOID VDP_VID_SetDsWincond3thr2                   (HI_U32 u32Data, HI_U32 ds_wincond3thr2);
HI_VOID VDP_VID_SetDsWincond3val3                   (HI_U32 u32Data, HI_U32 ds_wincond3val3);
HI_VOID VDP_VID_SetDsWincond3val4                   (HI_U32 u32Data, HI_U32 ds_wincond3val4);
HI_VOID VDP_VID_SetDsWincond3scl1                   (HI_U32 u32Data, HI_U32 ds_wincond3scl1);
HI_VOID VDP_VID_SetDsWincond4thr1                   (HI_U32 u32Data, HI_U32 ds_wincond4thr1);
HI_VOID VDP_VID_SetDsWincond4thr2                   (HI_U32 u32Data, HI_U32 ds_wincond4thr2);
HI_VOID VDP_VID_SetDsWincond4val1                   (HI_U32 u32Data, HI_U32 ds_wincond4val1);
HI_VOID VDP_VID_SetDsWincond4val2                   (HI_U32 u32Data, HI_U32 ds_wincond4val2);
HI_VOID VDP_VID_SetDsWincond4val3                   (HI_U32 u32Data, HI_U32 ds_wincond4val3);
HI_VOID VDP_VID_SetDsWincond4val4                   (HI_U32 u32Data, HI_U32 ds_wincond4val4);
HI_VOID VDP_VID_SetDsWincond4val5                   (HI_U32 u32Data, HI_U32 ds_wincond4val5);
HI_VOID VDP_VID_SetDsWincond4scl1                   (HI_U32 u32Data, HI_U32 ds_wincond4scl1);
HI_VOID VDP_VID_SetDsWincond5thr1                   (HI_U32 u32Data, HI_U32 ds_wincond5thr1);
HI_VOID VDP_VID_SetDsWincond5val1                   (HI_U32 u32Data, HI_U32 ds_wincond5val1);
HI_VOID VDP_VID_SetDsWincond5val2                   (HI_U32 u32Data, HI_U32 ds_wincond5val2);
HI_VOID VDP_VID_SetDsWincond5val3                   (HI_U32 u32Data, HI_U32 ds_wincond5val3);
HI_VOID VDP_VID_SetDsWincond5scl1                   (HI_U32 u32Data, HI_U32 ds_wincond5scl1);
HI_VOID VDP_VID_SetDsWincond5scl2                   (HI_U32 u32Data, HI_U32 ds_wincond5scl2);
HI_VOID VDP_VID_SetDsPicresscl0                     (HI_U32 u32Data, HI_U32 ds_picresscl0);
HI_VOID VDP_VID_SetDsPicresscl1                     (HI_U32 u32Data, HI_U32 ds_picresscl1);
HI_VOID VDP_VID_SetDsPicresscl2                     (HI_U32 u32Data, HI_U32 ds_picresscl2);
HI_VOID VDP_VID_SetDsWinactthr                      (HI_U32 u32Data, HI_U32 ds_winactthr);
HI_VOID VDP_VID_SetDsPicresofst                     (HI_U32 u32Data, HI_U32 ds_picresofst);
HI_VOID VDP_VID_SetDsPatcond6norm61                 (HI_U32 u32Data, HI_U32 ds_patcond6norm61);
HI_VOID VDP_VID_SetDsPatcond6norm62                 (HI_U32 u32Data, HI_U32 ds_patcond6norm62);
HI_VOID VDP_VID_SetDsPatcond6norm63                 (HI_U32 u32Data, HI_U32 ds_patcond6norm63);
HI_VOID VDP_VID_SetDsPatcond6normofst               (HI_U32 u32Data, HI_U32 ds_patcond6normofst);
HI_VOID VDP_VID_SetDsPatcond6norm5                  (HI_U32 u32Data, HI_U32 ds_patcond6norm5);
HI_VOID VDP_VID_SetDsPatcond6norm6                  (HI_U32 u32Data, HI_U32 ds_patcond6norm6);
HI_VOID VDP_VID_SetDsPatcond6clipscl6               (HI_U32 u32Data, HI_U32 ds_patcond6clipscl6);
HI_VOID VDP_VID_SetDsPatcond6ofst                   (HI_U32 u32Data, HI_U32 ds_patcond6ofst);
HI_VOID VDP_VID_SetDsSclctrst                       (HI_U32 u32Data, HI_U32 ds_sclctrst);
HI_VOID VDP_VID_SetDsResadpten                      (HI_U32 u32Data, HI_U32 ds_resadpten);
HI_VOID VDP_VID_SetDsShtctrstscl1                   (HI_U32 u32Data, HI_U32 ds_shtctrstscl1);
HI_VOID VDP_VID_SetDsShtctrstscl2                   (HI_U32 u32Data, HI_U32 ds_shtctrstscl2);
HI_VOID VDP_VID_SetDsCormmthr0                      (HI_U32 u32Data, HI_U32 ds_cormmthr0);
HI_VOID VDP_VID_SetDsCormmthr1                      (HI_U32 u32Data, HI_U32 ds_cormmthr1);
HI_VOID VDP_VID_SetDsPixeldiff2p                    (HI_U32 u32Data, HI_U32 ds_pixeldiff_2p);
HI_VOID VDP_VID_SetDsFlag2p                         (HI_U32 u32Data, HI_U32 ds_flag_2p);
HI_VOID VDP_VID_SetDsStrctrast2p                    (HI_U32 u32Data, HI_U32 ds_strctrast_2p);
HI_VOID VDP_VID_SetDsPatcond6ofst5                  (HI_U32 u32Data, HI_U32 ds_patcond6ofst5);
HI_VOID VDP_VID_SetDsPatcond6ofst6                  (HI_U32 u32Data, HI_U32 ds_patcond6ofst6);
HI_VOID VDP_VID_SetDsPatcond6ofst61                 (HI_U32 u32Data, HI_U32 ds_patcond6ofst61);
HI_VOID VDP_VID_SetDsPatcond6scl7                   (HI_U32 u32Data, HI_U32 ds_patcond6scl7);
HI_VOID VDP_VID_SetDsPatcond6ofst63                 (HI_U32 u32Data, HI_U32 ds_patcond6ofst63);
HI_VOID VDP_VID_SetDsPatcond6ofst62                 (HI_U32 u32Data, HI_U32 ds_patcond6ofst62);
HI_VOID VDP_VID_SetDsOvershootflag                  (HI_U32 u32Data, HI_U32 ds_overshootflag);

HI_VOID VDP_VID_SetDrEnnosmoothwavepro              (HI_U32 u32Data, HI_U32 dr_ennosmoothwavepro);
HI_VOID VDP_VID_SetDrEn3x3filter                    (HI_U32 u32Data, HI_U32 dr_en3x3filter);
HI_VOID VDP_VID_SetDrEnfarthestsmooth               (HI_U32 u32Data, HI_U32 dr_enfarthestsmooth);
HI_VOID VDP_VID_SetDrEnlimitpro                     (HI_U32 u32Data, HI_U32 dr_enlimitpro);
HI_VOID VDP_VID_SetDrEnunderpro                     (HI_U32 u32Data, HI_U32 dr_enunderpro);
HI_VOID VDP_VID_SetDrEncondarkpro                   (HI_U32 u32Data, HI_U32 dr_encondarkpro);
HI_VOID VDP_VID_SetDrEnconpro                       (HI_U32 u32Data, HI_U32 dr_enconpro);
HI_VOID VDP_VID_SetDrGradmaxthd                     (HI_U32 u32Data, HI_U32 dr_gradmaxthd);
HI_VOID VDP_VID_SetDrShootmaxthd                    (HI_U32 u32Data, HI_U32 dr_shootmaxthd);
HI_VOID VDP_VID_SetDrGradratio                      (HI_U32 u32Data, HI_U32 dr_gradratio);
HI_VOID VDP_VID_SetDrUnderratio                     (HI_U32 u32Data, HI_U32 dr_underratio);
HI_VOID VDP_VID_SetDrSrhtrsngradalpha               (HI_U32 u32Data, HI_U32 dr_srhtrsngradalpha);
HI_VOID VDP_VID_SetDrSrhtrsngradbeta                (HI_U32 u32Data, HI_U32 dr_srhtrsngradbeta);
HI_VOID VDP_VID_SetDrHighfrequent                   (HI_U32 u32Data, HI_U32 dr_highfrequent);
HI_VOID VDP_VID_SetDrRingx0                         (HI_U32 u32Data, HI_U32 dr_ringx0);
HI_VOID VDP_VID_SetDrRingx1                         (HI_U32 u32Data, HI_U32 dr_ringx1);
HI_VOID VDP_VID_SetDrRingx2                         (HI_U32 u32Data, HI_U32 dr_ringx2);
HI_VOID VDP_VID_SetDrRingx3                         (HI_U32 u32Data, HI_U32 dr_ringx3);
HI_VOID VDP_VID_SetDrRingy0                         (HI_U32 u32Data, HI_U32 dr_ringy0);
HI_VOID VDP_VID_SetDrRingy1                         (HI_U32 u32Data, HI_U32 dr_ringy1);
HI_VOID VDP_VID_SetDrRingy2                         (HI_U32 u32Data, HI_U32 dr_ringy2);
HI_VOID VDP_VID_SetDrRingy3                         (HI_U32 u32Data, HI_U32 dr_ringy3);
HI_VOID VDP_VID_SetDrShttornum0                     (HI_U32 u32Data, HI_U32 dr_shttornum0);
HI_VOID VDP_VID_SetDrShttornum1                     (HI_U32 u32Data, HI_U32 dr_shttornum1);
HI_VOID VDP_VID_SetDrRingk0                         (HI_U32 u32Data, HI_U32 dr_ringk0);
HI_VOID VDP_VID_SetDrShttornum2                     (HI_U32 u32Data, HI_U32 dr_shttornum2);
HI_VOID VDP_VID_SetDrShttornum3                     (HI_U32 u32Data, HI_U32 dr_shttornum3);
HI_VOID VDP_VID_SetDrRestornum                      (HI_U32 u32Data, HI_U32 dr_restornum);
HI_VOID VDP_VID_SetDrRingk1                         (HI_U32 u32Data, HI_U32 dr_ringk1);
HI_VOID VDP_VID_SetDrRingmax                        (HI_U32 u32Data, HI_U32 dr_ringmax);
HI_VOID VDP_VID_SetDrRingk2                         (HI_U32 u32Data, HI_U32 dr_ringk2);
HI_VOID VDP_VID_SetDrRingmin                        (HI_U32 u32Data, HI_U32 dr_ringmin);
HI_VOID VDP_VID_SetDrEstresalterthd                 (HI_U32 u32Data, HI_U32 dr_estresalterthd);
HI_VOID VDP_VID_SetDrEstresaltertmp                 (HI_U32 u32Data, HI_U32 dr_estresaltertmp);
HI_VOID VDP_VID_SetDrEstproringthd                  (HI_U32 u32Data, HI_U32 dr_estproringthd);
HI_VOID VDP_VID_SetDrShtsmooththd0                  (HI_U32 u32Data, HI_U32 dr_shtsmooththd0);
HI_VOID VDP_VID_SetDrShtsmooththd1                  (HI_U32 u32Data, HI_U32 dr_shtsmooththd1);
HI_VOID VDP_VID_SetDrShtsmooththd2                  (HI_U32 u32Data, HI_U32 dr_shtsmooththd2);
HI_VOID VDP_VID_SetDrShtsmoothvalue0                (HI_U32 u32Data, HI_U32 dr_shtsmoothvalue0);
HI_VOID VDP_VID_SetDrShtsmoothvalue1                (HI_U32 u32Data, HI_U32 dr_shtsmoothvalue1);
HI_VOID VDP_VID_SetDrShtsmoothvalue2                (HI_U32 u32Data, HI_U32 dr_shtsmoothvalue2);
HI_VOID VDP_VID_SetDrEstprogradthd1                 (HI_U32 u32Data, HI_U32 dr_estprogradthd1);
HI_VOID VDP_VID_SetDrEstprogradthd0                 (HI_U32 u32Data, HI_U32 dr_estprogradthd0);
HI_VOID VDP_VID_SetDrEstprogradcoef                 (HI_U32 u32Data, HI_U32 dr_estprogradcoef);
HI_VOID VDP_VID_SetDrEstcomthd                      (HI_U32 u32Data, HI_U32 dr_estcomthd);
HI_VOID VDP_VID_SetDrEstcomratio1                   (HI_U32 u32Data, HI_U32 dr_estcomratio1);
HI_VOID VDP_VID_SetDrEstcomratio2                   (HI_U32 u32Data, HI_U32 dr_estcomratio2);
HI_VOID VDP_VID_SetDrEstcomtmp                      (HI_U32 u32Data, HI_U32 dr_estcomtmp);
HI_VOID VDP_VID_SetDrEstpixeldiff                   (HI_U32 u32Data, HI_U32 dr_estpixeldiff);
HI_VOID VDP_VID_SetDrLimitwavescope0                (HI_U32 u32Data, HI_U32 dr_limitwavescope0);
HI_VOID VDP_VID_SetDrLimitwavescope1                (HI_U32 u32Data, HI_U32 dr_limitwavescope1);
HI_VOID VDP_VID_SetDrLimitwavenum0                  (HI_U32 u32Data, HI_U32 dr_limitwavenum0);
HI_VOID VDP_VID_SetDrLimitwavenum1                  (HI_U32 u32Data, HI_U32 dr_limitwavenum1);
HI_VOID VDP_VID_SetDrLimitwavenum2                  (HI_U32 u32Data, HI_U32 dr_limitwavenum2);
HI_VOID VDP_VID_SetDrLimitgrad                      (HI_U32 u32Data, HI_U32 dr_limitgrad);
HI_VOID VDP_VID_SetDrLimitscope                     (HI_U32 u32Data, HI_U32 dr_limitscope);
HI_VOID VDP_VID_SetDrCalcsum5error                  (HI_U32 u32Data, HI_U32 dr_calcsum5error);
HI_VOID VDP_VID_SetDrLargewaveblend                 (HI_U32 u32Data, HI_U32 dr_largewaveblend);
HI_VOID VDP_VID_SetDrLargewavesumblend              (HI_U32 u32Data, HI_U32 dr_largewavesumblend);
HI_VOID VDP_VID_SetDrPixelrange                     (HI_U32 u32Data, HI_U32 dr_pixelrange);
HI_VOID VDP_VID_SetDrCalcwaverange                  (HI_U32 u32Data, HI_U32 dr_calcwaverange);
HI_VOID VDP_VID_SetDrLargewaveminthd                (HI_U32 u32Data, HI_U32 dr_largewaveminthd);
HI_VOID VDP_VID_SetDrWavepronumlim                  (HI_U32 u32Data, HI_U32 dr_wavepronumlim);
HI_VOID VDP_VID_SetDrSmoothblendx0                  (HI_U32 u32Data, HI_U32 dr_smoothblendx0);
HI_VOID VDP_VID_SetDrSmoothblendx1                  (HI_U32 u32Data, HI_U32 dr_smoothblendx1);
HI_VOID VDP_VID_SetDrSmoothblendx2                  (HI_U32 u32Data, HI_U32 dr_smoothblendx2);
HI_VOID VDP_VID_SetDrSmoothblendx3                  (HI_U32 u32Data, HI_U32 dr_smoothblendx3);
HI_VOID VDP_VID_SetDrSmoothblendy0                  (HI_U32 u32Data, HI_U32 dr_smoothblendy0);
HI_VOID VDP_VID_SetDrSmoothblendy1                  (HI_U32 u32Data, HI_U32 dr_smoothblendy1);
HI_VOID VDP_VID_SetDrSmoothblendy2                  (HI_U32 u32Data, HI_U32 dr_smoothblendy2);
HI_VOID VDP_VID_SetDrSmoothblendy3                  (HI_U32 u32Data, HI_U32 dr_smoothblendy3);
HI_VOID VDP_VID_SetDrSmoothblendmax                 (HI_U32 u32Data, HI_U32 dr_smoothblendmax);
HI_VOID VDP_VID_SetDrSmoothblendk0                  (HI_U32 u32Data, HI_U32 dr_smoothblendk0);
HI_VOID VDP_VID_SetDrSmoothblendmin                 (HI_U32 u32Data, HI_U32 dr_smoothblendmin);
HI_VOID VDP_VID_SetDrSmoothblendk1                  (HI_U32 u32Data, HI_U32 dr_smoothblendk1);
HI_VOID VDP_VID_SetDrNoflagareablend                (HI_U32 u32Data, HI_U32 dr_noflagareablend);
HI_VOID VDP_VID_SetDrSmoothblendk2                  (HI_U32 u32Data, HI_U32 dr_smoothblendk2);
HI_VOID VDP_VID_SetDrPixellargeerror                (HI_U32 u32Data, HI_U32 dr_pixellargeerror);
HI_VOID VDP_VID_SetDrConpixelerror                  (HI_U32 u32Data, HI_U32 dr_conpixelerror);
HI_VOID VDP_VID_SetDrCon5pixelerror                 (HI_U32 u32Data, HI_U32 dr_con5pixelerror);
HI_VOID VDP_VID_SetDrConallpixelerror               (HI_U32 u32Data, HI_U32 dr_conallpixelerror);
HI_VOID VDP_VID_SetDrReturnblend                    (HI_U32 u32Data, HI_U32 dr_returnblend);
HI_VOID VDP_VID_SetDrConsumblend                    (HI_U32 u32Data, HI_U32 dr_consumblend);
HI_VOID VDP_VID_SetDrLimitpixelnum                  (HI_U32 u32Data, HI_U32 dr_limitpixelnum);
HI_VOID VDP_VID_SetDrLimitsmoothpronum              (HI_U32 u32Data, HI_U32 dr_limitsmoothpronum);
HI_VOID VDP_VID_SetDrLimitwavepronum                (HI_U32 u32Data, HI_U32 dr_limitwavepronum);
HI_VOID VDP_VID_SetDrCrossblend                     (HI_U32 u32Data, HI_U32 dr_crossblend);
HI_VOID VDP_VID_SetDrShootblend                     (HI_U32 u32Data, HI_U32 dr_shootblend);
HI_VOID VDP_VID_SetDrBorderprcwidth                 (HI_U32 u32Data, HI_U32 dr_borderprcwidth);
HI_VOID VDP_VID_SetDrResblend                       (HI_U32 u32Data, HI_U32 dr_resblend);
HI_VOID VDP_VID_SetDBBordFlag                       (HI_U32 u32Data,HI_U32 bordflag128[128]);

HI_VOID VDP_VID_SetTnrWbcEnable                     (HI_U32 u32Data, HI_U32 u32Enable);
HI_VOID VDP_VID_SetTnrWbcRegUp                      (HI_U32 u32Data);
HI_VOID VDP_VID_SetTnrWbcAddr                       (HI_U32 u32Data, HI_U32 u32YAddr, HI_U32 u32CAddr);
HI_VOID VDP_VID_SetTnrWbcStride                     (HI_U32 u32Data, HI_U32 u32YStride, HI_U32 u32CStride );
HI_VOID VDP_VID_SetMadWbcEnable                     (HI_U32 u32Data, HI_U32 u32Enable);
HI_VOID VDP_VID_SetMadWbcRegUp                      (HI_U32 u32Data);
HI_VOID VDP_VID_SetMadWbcAddr                       (HI_U32 u32Data, HI_U32 u32YAddr);
HI_VOID VDP_VID_SetMadWbcStride                     (HI_U32 u32Data, HI_U32 u32YStride);
HI_VOID VDP_VID_SetDbmCfgAddr                       (HI_U32 u32Data, HI_U32 u32Addr);
HI_VOID VDP_VID_SetSnrCfgAddr                       (HI_U32 u32Data, HI_U32 u32Addr);
HI_VOID VDP_VID_SetTnrCfgAddr                       (HI_U32 u32Data, HI_U32 u32Addr);
HI_VOID VDP_VID_SetTnrLutAddr                       (HI_U32 u32Data, HI_U32 u32Addr);
HI_VOID VDP_VID_SetTnrPreAddr                       (HI_U32 u32Data, HI_U32 u32LAddr, HI_U32 u32CAddr, HI_U32 u32LStr, HI_U32 u32CStr);
HI_VOID VDP_VID_SetTnrMadAddr                       (HI_U32 u32Data, HI_U32 u32LAddr, HI_U32 u32LStr);
HI_VOID VDP_VID_SetDbmAddr                          (HI_U32 u32Data, HI_U32 u32CAddr, HI_U32 u32CStr);
HI_VOID VDP_VID_SetWbcTnrPreSmmuLBypass             (HI_U32 u32Data, HI_U32 u32Bypass);
HI_VOID VDP_VID_SetWbcTnrMadSmmuBypass              (HI_U32 u32Data, HI_U32 u32Bypass);
HI_VOID VDP_VID_SetWbcTnrSttSmmuBypass              (HI_U32 u32Data, HI_U32 u32Bypass);
HI_VOID VDP_VID_SetWbcTnrPreSmmuCBypass             (HI_U32 u32Data, HI_U32 u32Bypass);
HI_VOID VDP_VID_SetDbmInfoReso                      (HI_U32 u32Data, VDP_RECT_S  stRect);
HI_VOID VDP_VID_SetDbmInfoEnable                    (HI_U32 u32Data, HI_U32  dbm_info_en);
HI_VOID VDP_VID_SetTnrWbcCEnable                    (HI_U32 u32Data, HI_U32 u32Enable);
HI_VOID VDP_VID_SetTnrMadDataMode                   (HI_U32 u32Data, HI_U32 mad_data_mode);
HI_VOID VDP_VID_SetMadWbcDataMode                   (HI_U32 u32Data, HI_U32 mad_data_mode);
HI_VOID VDP_VID_SetTnrCEnable                       (HI_U32 u32Data, HI_U32 tnr_c_en);
HI_VOID VDP_VID_SetSttWbcAddr                       (HI_U32 u32Data, HI_U32 u32YAddr);
HI_VOID VDP_VID_SetSttWbcStride                     (HI_U32 u32Data, HI_U32 u32YStride);
HI_VOID VDP_VID_SetTnrWbcDitherEnable               (HI_U32 u32Data, HI_U32 u32Enable);
HI_VOID VDP_VID_SetTnrWbcDitherMode                 (HI_U32 u32Data, HI_U32 u32Mode);
HI_VOID VDP_VID_SetTnrWbcDitherRound                (HI_U32 u32Data, HI_U32 u32Round);
HI_VOID VDP_VID_SetTnrWbcDataWidth                  (HI_U32 u32Data, HI_U32 u32DataWidth);
HI_VOID VDP_VID_SetRefDcmpEnable                    (HI_U32 u32Data, HI_U32 u32bEnable);
HI_VOID VDP_VID_SetTnrWbcCmpEnable                  (HI_U32 u32Data, HI_U32 u32bEnable);
#endif
