#ifndef __HAL_SPEC_DEFINE_H
#define __HAL_SPEC_DEFINE_H

typedef enum tagDISP_INTERRUPT_E
{
    DISP_INTERRUPT_NONE = 0,
    DISP_INTERRUPT_D0_0_PERCENT  = 0x10,
    DISP_INTERRUPT_D0_90_PERCENT = 0x20,
    DISP_INTERRUPT_D0_100_PERCENT = 0x40,
    DISP_INTERRUPT_D0_UFINT      = 0x80,

    DISP_INTERRUPT_D1_0_PERCENT  = 0x1,
    DISP_INTERRUPT_D1_90_PERCENT = 0x2,
    DISP_INTERRUPT_D1_100_PERCENT = 0x4,
    DISP_INTERRUPT_D1_UFINT      = 0x8,

    DISP_INTERRUPT_WBCDHD_PARTFNI  = 0x20000000,

    DISP_INTERRUPT_GP1_RES       = 0x100,
    DISP_INTERRUPT_MC1_UFINT     = 0x200,
	DISP_INTERRUPT_WBC_VP	 = 0x800,

    DISP_INTERRUPT_ALL           = 0xFFFFFFFF,
}DISP_INTERRUPT_E;
#endif
